import type { DataSourceCardSpec, DataSourceSectionSpec, DataSourceSpec } from "./dataSourceTypes";
import {
  DATA_SOURCE_DEMO_GOOGLE_ADS_CARD_CONNECTED,
  DATA_SOURCE_DEMO_TIKTOK_CARD_CONNECTED,
} from "./dataSourceDemoConfig";

export const GOOGLE_ADS_SPEC: DataSourceSpec = {
  id: "google-ads",
  name: "Google Ads",
  category: "广告生态",
  logoText: "Google",
  logoAssetId: "google-ads",
  description: "同步 Google Ads 广告账户、广告系列与投放数据，用于统一分析和后续字段映射。",
  breadcrumbs: ["数据融合", "通用数据接入", "数据源管理", "Google Ads"],
  infoPanel: {
    helpDocLabel: "帮助文档",
    sectionTitle: "需要的信息",
    requiredInfo: ["Developer Token", "OAuth 凭证", "客户 ID 映射"],
    footnote: "以上信息根据不同的应用需要填写的内容略有不同，请根据具体应用填写",
  },
  connectionList: {
    searchPlaceholder: "搜索连接名称或连接 ID",
    statuses: [
      { value: "enabled", label: "启用", tone: "success" },
      { value: "disabled", label: "停用", tone: "default" },
    ],
    actions: [
      { key: "detail", label: "详情" },
      { key: "toggleStatus", label: "启用/禁用", enabledLabel: "禁用", disabledLabel: "启用" },
      { key: "delete", label: "删除", disabledWhenStatus: ["enabled"] },
    ],
    emptyState: {
      title: "暂无连接",
      description: "创建连接后，可在此管理 Google Ads 数据连接。",
      actionLabel: "创建连接",
    },
    searchEmptyState: {
      title: "未找到匹配连接",
      description: "请调整搜索关键词后重试。",
    },
    columns: [
      { key: "connectionId", title: "连接 ID", type: "number", dataIndex: "connectionId", width: 128, sortable: true },
      { key: "name", title: "连接名称", type: "text", dataIndex: "name", ellipsis: true, sortable: true },
      { key: "status", title: "状态", type: "status", dataIndex: "status", width: 128, sortable: true },
      {
        key: "adAccountCount",
        title: "Google Ads 客户 ID 数",
        type: "number",
        dataIndex: "adAccountCount",
        width: 180,
        sortable: true,
        align: "left",
      },
      { key: "creator", title: "创建人", type: "text", dataIndex: "creator", width: 140, sortable: true },
      { key: "createdAt", title: "创建时间", type: "datetime", dataIndex: "createdAt", width: 191, sortable: true },
      { key: "action", title: "操作", type: "actions", width: 160 },
    ],
    mockData: [
      {
        key: "1",
        connectionId: 1,
        name: "Google_Ads_Global",
        status: "enabled",
        adAccountCount: 3,
        creator: "李郁文",
        createdAt: "2026-07-03 10:30:00",
      },
      {
        key: "2",
        connectionId: 2,
        name: "Google_Ads_Backup",
        status: "disabled",
        adAccountCount: 1,
        creator: "李郁文",
        createdAt: "2026-07-03 11:20:00",
      },
    ],
  },
  createConnection: {
    title: "创建数据源连接",
    submitLabel: "创建",
    fields: [
      {
        key: "connectionName",
        label: "连接名称",
        type: "input",
        required: true,
        placeholder: "请输入连接名称",
      },
      {
        key: "developerToken",
        label: "Developer Token",
        type: "password",
        required: true,
        placeholder: "请输入 Developer Token",
      },
      {
        key: "clientId",
        label: "Client ID",
        type: "input",
        required: true,
        placeholder: "请输入 Client ID",
      },
      {
        key: "clientSecret",
        label: "Client Secret",
        type: "password",
        required: true,
        placeholder: "请输入 Client Secret",
      },
      {
        key: "refreshToken",
        label: "Refresh Token",
        type: "password",
        required: true,
        placeholder: "请输入 Refresh Token",
      },
    ],
    accountMapping: {
      title: "Google Ads 账号映射",
      description: "将 Google Ads 客户 ID 映射到系统中的广告账号。",
      sourceLabel: "请选择 Google Ads 客户 ID",
      targetLabel: "请选择系统广告账号",
      sourceOptions: ["123-456-7890", "234-567-8901", "345-678-9012"],
      targetOptions: ["华东广告账号", "华南广告账号", "海外广告账号"],
      addLabel: "添加账号映射",
    },
  },
};

export const TIKTOK_ADS_SPEC: DataSourceSpec = {
  id: "tiktok-ads",
  name: "TikTok Ads",
  category: "广告营销",
  logoText: "TikTok",
  logoAssetId: "tiktok-ads",
  description: "同步 TikTok Ads 广告账户、广告系列与投放数据，用于统一分析和后续字段映射。",
  breadcrumbs: ["数据融合", "通用数据接入", "数据源管理", "TikTok Ads"],
  infoPanel: {
    helpDocLabel: "帮助文档",
    sectionTitle: "需要的信息",
    requiredInfo: ["账号授权信息", "广告账户", "字段映射"],
    footnote: "以上信息根据不同的应用需要填写的内容略有不同，请根据具体应用填写",
  },
  connectionList: {
    searchPlaceholder: "搜索连接名称或服务器地址",
    statuses: [
      { value: "enabled", label: "启用", tone: "success" },
      { value: "disabled", label: "停用", tone: "default" },
    ],
    actions: [
      { key: "detail", label: "详情" },
      { key: "toggleStatus", label: "启用/禁用", enabledLabel: "禁用", disabledLabel: "启用" },
      { key: "delete", label: "删除", disabledWhenStatus: ["enabled"] },
    ],
    emptyState: {
      title: "暂无连接",
      description: "创建连接后，可在此管理 TikTok Ads 数据连接。",
      actionLabel: "创建连接",
    },
    searchEmptyState: {
      title: "未找到匹配连接",
      description: "请调整搜索关键词后重试。",
    },
    columns: [
      { key: "connectionId", title: "连接 ID", type: "number", dataIndex: "connectionId", width: 128, sortable: true },
      { key: "name", title: "连接名称", type: "text", dataIndex: "name", ellipsis: true, sortable: true },
      { key: "status", title: "状态", type: "status", dataIndex: "status", width: 128, sortable: true },
      {
        key: "adAccountCount",
        title: "广告账号数量",
        type: "number",
        dataIndex: "adAccountCount",
        width: 149,
        sortable: true,
        align: "left",
      },
      { key: "creator", title: "创建人", type: "text", dataIndex: "creator", width: 140, sortable: true },
      { key: "createdAt", title: "创建时间", type: "datetime", dataIndex: "createdAt", width: 191, sortable: true },
      { key: "action", title: "操作", type: "actions", width: 160 },
    ],
    mockData: [
      {
        key: "2",
        connectionId: 2,
        name: "TikTok_APAC_Test",
        status: "enabled",
        adAccountCount: 12,
        creator: "李郁文",
        createdAt: "2023-09-18 11:00:12",
      },
      {
        key: "1",
        connectionId: 1,
        name: "TikTok_Global_Backup",
        status: "disabled",
        adAccountCount: 3,
        creator: "李郁文",
        createdAt: "2023-09-18 11:00:12",
      },
    ],
  },
  createConnection: {
    title: "创建数据源连接",
    submitLabel: "创建",
    fields: [
      {
        key: "connectionName",
        label: "数据源连接名称",
        type: "input",
        required: true,
        placeholder: "请输入",
      },
      {
        key: "appId",
        label: "app_id",
        type: "input",
        required: true,
        placeholder: "请输入",
      },
      {
        key: "appSecret",
        label: "app_secret",
        type: "password",
        required: true,
        placeholder: "请输入",
      },
      {
        key: "accessToken",
        label: "Access Token",
        type: "password",
        required: true,
        placeholder: "请输入",
      },
      {
        key: "remark",
        label: "备注",
        type: "textarea",
        placeholder: "请输入",
      },
    ],
    accountMapping: {
      title: "账号映射",
      description: "将 TikTok Ads 广告账号映射到神策项目，用于后续数据同步。",
      sourceLabel: "TikTok Ads 广告账号",
      targetLabel: "神策项目",
      sourceOptions: ["TikTok_APAC_Account", "TikTok_Global_Account"],
      targetOptions: ["正式项目", "测试项目"],
      addLabel: "添加映射",
    },
  },
};

export const DATA_SOURCE_INGESTION_SECTIONS: DataSourceSectionSpec[] = [
  {
    id: "ad-ecosystem",
    title: "广告生态",
    count: 6,
    cards: [
      {
        id: "facebook-ads",
        name: "Meta Ads",
        category: "广告生态",
        logoText: "Meta",
        logoAssetId: "facebook-ads",
        connected: true,
        connectionCount: 0,
        countUnit: "connections",
        beta: true,
      },
      {
        id: GOOGLE_ADS_SPEC.id,
        name: GOOGLE_ADS_SPEC.name,
        category: "广告生态",
        logoText: GOOGLE_ADS_SPEC.logoText,
        logoAssetId: GOOGLE_ADS_SPEC.logoAssetId,
        connected: DATA_SOURCE_DEMO_GOOGLE_ADS_CARD_CONNECTED,
        connectionCount: DATA_SOURCE_DEMO_GOOGLE_ADS_CARD_CONNECTED ? 1 : undefined,
        countUnit: "connections",
        beta: true,
        navigable: true,
      },
      {
        id: TIKTOK_ADS_SPEC.id,
        name: "TikTok ads",
        category: "广告生态",
        logoText: TIKTOK_ADS_SPEC.logoText,
        logoAssetId: TIKTOK_ADS_SPEC.id,
        connected: DATA_SOURCE_DEMO_TIKTOK_CARD_CONNECTED,
        connectionCount: DATA_SOURCE_DEMO_TIKTOK_CARD_CONNECTED ? 1 : undefined,
        countUnit: "connections",
        navigable: true,
      },
      {
        id: "xiaomi",
        name: "小米",
        category: "广告生态",
        logoText: "小米",
        logoAssetId: "xiaomi",
        connected: true,
        connectionCount: 1,
        countUnit: "applications",
      },
      {
        id: "getui",
        name: "个推",
        category: "广告生态",
        logoText: "个推",
        logoAssetId: "getui",
        connected: true,
        connectionCount: 1,
        countUnit: "applications",
      },
      {
        id: "jiguang",
        name: "极光",
        category: "广告生态",
        logoText: "极光",
        logoAssetId: "jiguang",
        connected: true,
        connectionCount: 1,
        countUnit: "applications",
      },
    ],
  },
];

/** @deprecated 使用 `DATA_SOURCE_INGESTION_SECTIONS` */
export const DATA_SOURCE_CARDS: DataSourceCardSpec[] = DATA_SOURCE_INGESTION_SECTIONS.flatMap(
  (section) => section.cards,
);
