import type { ComponentType } from "react";
import type { IconCategory, RegistryIconRenderProps } from "./types";
import type { IconRegistryEntry } from "./registry";
import { FIGMA_ICON_NAMES, type FigmaIconName } from "./figma-icon-names";

const FIGMA_ICON_ASSETS: Record<FigmaIconName, string> = {
  "bold": "/icons/bold.svg",
  "strikethrough": "/icons/strikethrough.svg",
  "stroke-none": "/icons/stroke-none.svg",
  "stroke-solid": "/icons/stroke-solid.svg",
  "stroke-dash": "/icons/stroke-dash.svg",
  "rich-text": "/icons/rich-text.svg",
  "align-top": "/icons/align-top.svg",
  "align-horizontal-center": "/icons/align-horizontal-center.svg",
  "align-bottom": "/icons/align-bottom.svg",
  "align-left": "/icons/align-left.svg",
  "align-vertical-center": "/icons/align-vertical-center.svg",
  "align-right": "/icons/align-right.svg",
  "distribute-horizontal-spacing": "/icons/distribute-horizontal-spacing.svg",
  "distribute-vertical-spacing": "/icons/distribute-vertical-spacing.svg",
  "underline": "/icons/underline.svg",
  "text-align-left": "/icons/text-align-left.svg",
  "text-align-right": "/icons/text-align-right.svg",
  "text-align-center": "/icons/text-align-center.svg",
  "text-align-justify": "/icons/text-align-justify.svg",
  "italic": "/icons/italic.svg",
  "underline-dotted": "/icons/underline-dotted.svg",
  "underline-wavy": "/icons/underline-wavy.svg",
  "overline": "/icons/overline.svg",
  "top-left-corner-rounded": "/icons/top-left-corner-rounded.svg",
  "top-right-corner-rounded": "/icons/top-right-corner-rounded.svg",
  "bottom-left-corner-rounded": "/icons/bottom-left-corner-rounded.svg",
  "bottom-right-corner-rounded": "/icons/bottom-right-corner-rounded.svg",
  "left-float": "/icons/left-float.svg",
  "right-float": "/icons/right-float.svg",
  "above-element": "/icons/above-element.svg",
  "under-of-element": "/icons/under-of-element.svg",
  "padding-left": "/icons/padding-left.svg",
  "padding-top": "/icons/padding-top.svg",
  "padding-bottom": "/icons/padding-bottom.svg",
  "padding-right": "/icons/padding-right.svg",
  "search": "/icons/search.svg",
  "recover": "/icons/recover.svg",
  "share": "/icons/share.svg",
  "zoom-in": "/icons/zoom-in.svg",
  "zoom-out": "/icons/zoom-out.svg",
  "drag-horizontal": "/icons/drag-horizontal.svg",
  "drag-vertical": "/icons/drag-vertical.svg",
  "visible": "/icons/visible.svg",
  "hiding": "/icons/hiding.svg",
  "attachment": "/icons/attachment.svg",
  "unpin": "/icons/unpin.svg",
  "pin": "/icons/pin.svg",
  "link": "/icons/link.svg",
  "calendar": "/icons/calendar.svg",
  "download": "/icons/download.svg",
  "copy": "/icons/copy.svg",
  "logout": "/icons/logout.svg",
  "connect": "/icons/connect.svg",
  "save": "/icons/save.svg",
  "filter": "/icons/filter.svg",
  "upload": "/icons/upload.svg",
  "power-off": "/icons/power-off.svg",
  "send": "/icons/send.svg",
  "fit-screen": "/icons/fit-screen.svg",
  "rename": "/icons/rename.svg",
  "delete": "/icons/delete.svg",
  "lock": "/icons/lock.svg",
  "unlock": "/icons/unlock.svg",
  "setting": "/icons/setting.svg",
  "edit": "/icons/edit.svg",
  "scan": "/icons/scan.svg",
  "add-chart": "/icons/add-chart.svg",
  "mark-as-read": "/icons/mark-as-read.svg",
  "convert": "/icons/convert.svg",
  "format": "/icons/format.svg",
  "execute": "/icons/execute.svg",
  "collect": "/icons/collect.svg",
  "import": "/icons/import.svg",
  "view": "/icons/view.svg",
  "filter-image": "/icons/filter-image.svg",
  "custom-size": "/icons/custom-size.svg",
  "code": "/icons/code.svg",
  "unfollow": "/icons/unfollow.svg",
  "table-expand": "/icons/table-expand.svg",
  "table-collapse": "/icons/table-collapse.svg",
  "card-view": "/icons/card-view.svg",
  "freeze": "/icons/freeze.svg",
  "describe": "/icons/describe.svg",
  "markers": "/icons/markers.svg",
  "optimize": "/icons/optimize.svg",
  "calendar-utc": "/icons/calendar-utc.svg",
  "filter-group": "/icons/filter-group.svg",
  "input-text": "/icons/input-text.svg",
  "expand": "/icons/expand.svg",
  "collapse": "/icons/collapse.svg",
  "newchat": "/icons/newchat.svg",
  "stop": "/icons/stop.svg",
  "maximize": "/icons/maximize.svg",
  "minimize": "/icons/minimize.svg",
  "thumbs-up": "/icons/thumbs-up.svg",
  "search-replace": "/icons/search-replace.svg",
  "strategy-search": "/icons/strategy-search.svg",
  "newchat-2": "/icons/newchat-2.svg",
  "linkto": "/icons/linkto.svg",
  "pause": "/icons/pause.svg",
  "execute-now": "/icons/execute-now.svg",
  "time": "/icons/time.svg",
  "mail": "/icons/mail.svg",
  "money": "/icons/money.svg",
  "person": "/icons/person.svg",
  "folder": "/icons/folder.svg",
  "remark": "/icons/remark.svg",
  "setting-batch-permission": "/icons/setting-batch-permission.svg",
  "emoji": "/icons/emoji.svg",
  "pop": "/icons/pop.svg",
  "page-navigation": "/icons/page-navigation.svg",
  "layer": "/icons/layer.svg",
  "page": "/icons/page.svg",
  "component": "/icons/component.svg",
  "web": "/icons/web.svg",
  "tablet": "/icons/tablet.svg",
  "home": "/icons/home.svg",
  "person-add": "/icons/person-add.svg",
  "text-type": "/icons/text-type.svg",
  "checkbox-small": "/icons/checkbox-small.svg",
  "check": "/icons/check.svg",
  "close": "/icons/close.svg",
  "help": "/icons/help.svg",
  "info": "/icons/info.svg",
  "more": "/icons/more.svg",
  "loading": "/icons/loading.svg",
  "man": "/icons/man.svg",
  "woman": "/icons/woman.svg",
  "q-r-code": "/icons/q-r-code.svg",
  "checkbox-line": "/icons/checkbox-line.svg",
  "icon-default": "/icons/icon-default.svg",
  "add": "/icons/add.svg",
  "vip": "/icons/vip.svg",
  "percentage": "/icons/percentage.svg",
  "vs": "/icons/vs.svg",
  "identifying-code": "/icons/identifying-code.svg",
  "editor-add": "/icons/editor-add.svg",
  "editor-minus": "/icons/editor-minus.svg",
  "editor-product-sign": "/icons/editor-product-sign.svg",
  "editor-sign-of-division": "/icons/editor-sign-of-division.svg",
  "editor-parenthesis-left": "/icons/editor-parenthesis-left.svg",
  "editor-parenthesis-right": "/icons/editor-parenthesis-right.svg",
  "editor-square-brackets-left": "/icons/editor-square-brackets-left.svg",
  "editor-square-brackets-right": "/icons/editor-square-brackets-right.svg",
  "width": "/icons/width.svg",
  "high": "/icons/high.svg",
  "up": "/icons/up.svg",
  "down": "/icons/down.svg",
  "left": "/icons/left.svg",
  "right": "/icons/right.svg",
  "to-top": "/icons/to-top.svg",
  "indent": "/icons/indent.svg",
  "outdent": "/icons/outdent.svg",
  "reload": "/icons/reload.svg",
  "arrow-doubule-left": "/icons/arrow-doubule-left.svg",
  "arrow-doubule-right": "/icons/arrow-doubule-right.svg",
  "indent-right": "/icons/indent-right.svg",
  "outdent-right": "/icons/outdent-right.svg",
  "z-to-a": "/icons/z-to-a.svg",
  "a-to-z": "/icons/a-to-z.svg",
  "number0-to-9": "/icons/number0-to-9.svg",
  "number9-to-0": "/icons/number9-to-0.svg",
  "revoke": "/icons/revoke.svg",
  "redo": "/icons/redo.svg",
  "reverse-order": "/icons/reverse-order.svg",
  "positive-sequence": "/icons/positive-sequence.svg",
  "sort-senior": "/icons/sort-senior.svg",
  "top": "/icons/top.svg",
  "bottom": "/icons/bottom.svg",
  "descendant": "/icons/descendant.svg",
  "ascendant": "/icons/ascendant.svg",
  "descendant-group": "/icons/descendant-group.svg",
  "ascendant-group": "/icons/ascendant-group.svg",
  "back-navigate": "/icons/back-navigate.svg",
  "next-level": "/icons/next-level.svg",
  "up-one-level": "/icons/up-one-level.svg",
  "expand-and-collapse-arrow-left": "/icons/expand-and-collapse-arrow-left.svg",
  "expand-and-collapse-arrow-right": "/icons/expand-and-collapse-arrow-right.svg",
  "arrow-right": "/icons/arrow-right.svg",
  "time-picker-right": "/icons/time-picker-right.svg",
  "android": "/icons/android.svg",
  "mini-program": "/icons/mini-program.svg",
  "wechat": "/icons/wechat.svg",
  "app": "/icons/app.svg",
  "html-5": "/icons/html-5.svg",
  "js": "/icons/js.svg",
  "sql": "/icons/sql.svg",
  "java": "/icons/java.svg",
  "wechat-work": "/icons/wechat-work.svg",
  "line": "/icons/line.svg",
  "alipay": "/icons/alipay.svg",
  "whatsapp": "/icons/whatsapp.svg",
  "chart-point": "/icons/chart-point.svg",
  "chart-bar": "/icons/chart-bar.svg",
  "chart-line": "/icons/chart-line.svg",
  "chart-grouped-bar": "/icons/chart-grouped-bar.svg",
  "chart-histogram": "/icons/chart-histogram.svg",
  "tree-association-node": "/icons/tree-association-node.svg",
  "tree-single-node": "/icons/tree-single-node.svg",
  "board-view": "/icons/board-view.svg",
  "sheet": "/icons/sheet.svg",
  "business-model": "/icons/business-model.svg",
  "chart": "/icons/chart.svg",
  "helpcenter": "/icons/helpcenter.svg",
  "notice": "/icons/notice.svg",
  "sbp": "/icons/sbp.svg",
  "workload-manager": "/icons/workload-manager.svg",
  "examine": "/icons/examine.svg",
  "phone": "/icons/phone.svg",
  "after-sale": "/icons/after-sale.svg",
  "diagnostic-tool": "/icons/diagnostic-tool.svg",
  "language": "/icons/language.svg",
  "personal": "/icons/personal.svg",
  "personal-sensitive-information": "/icons/personal-sensitive-information.svg",
  "operation-log": "/icons/operation-log.svg",
  "notification-center": "/icons/notification-center.svg",
  "query-queue": "/icons/query-queue.svg",
  "api-key": "/icons/api-key.svg",
  "csv": "/icons/csv.svg",
  "png": "/icons/png.svg",
  "pdf": "/icons/pdf.svg",
  "picture": "/icons/picture.svg",
  "file": "/icons/file.svg",
  "event": "/icons/event.svg",
  "event-propertie": "/icons/event-propertie.svg",
  "preset-property": "/icons/preset-property.svg",
  "tag": "/icons/tag.svg",
  "custom-property": "/icons/custom-property.svg",
  "user-group": "/icons/user-group.svg",
  "user-property": "/icons/user-property.svg",
  "all": "/icons/all.svg",
  "time-controller": "/icons/time-controller.svg",
  "audience-judgment": "/icons/audience-judgment.svg",
  "audience-real-time": "/icons/audience-real-time.svg",
  "event-unfinished": "/icons/event-unfinished.svg",
  "timed-single-entry": "/icons/timed-single-entry.svg",
  "timed-repeat-entry": "/icons/timed-repeat-entry.svg",
  "proportional-shunt": "/icons/proportional-shunt.svg",
  "webhook": "/icons/webhook.svg",
  "audience-shunt": "/icons/audience-shunt.svg",
  "period-shunt": "/icons/period-shunt.svg",
  "event-shunt": "/icons/event-shunt.svg",
  "goal": "/icons/goal.svg",
  "archive": "/icons/archive.svg",
  "number": "/icons/number.svg",
  "bool": "/icons/bool.svg",
  "string": "/icons/string.svg",
  "list": "/icons/list.svg",
  "object-array": "/icons/object-array.svg",
  "datetime": "/icons/datetime.svg",
  "template-picture-and-text": "/icons/template-picture-and-text.svg",
  "template-multiple-pictures-and-text": "/icons/template-multiple-pictures-and-text.svg",
  "template-hot-zone": "/icons/template-hot-zone.svg",
  "template-text": "/icons/template-text.svg",
  "template-custom": "/icons/template-custom.svg",
  "template-picture": "/icons/template-picture.svg",
  "template-multigraph": "/icons/template-multigraph.svg",
  "key": "/icons/key.svg",
  "relation": "/icons/relation.svg",
  "no-correlation": "/icons/no-correlation.svg",
  "dimension": "/icons/dimension.svg",
  "membership": "/icons/membership.svg",
  "list-letter": "/icons/list-letter.svg",
  "detail-number": "/icons/detail-number.svg",
  "detail-letter": "/icons/detail-letter.svg",
  "detail-time": "/icons/detail-time.svg",
  "computed-column": "/icons/computed-column.svg",
  "time-macro": "/icons/time-macro.svg",
  "mode-key": "/icons/mode-key.svg",
  "mode-automatic": "/icons/mode-automatic.svg",
  "group-management": "/icons/group-management.svg",
  "filter-list": "/icons/filter-list.svg",
  "template-operation": "/icons/template-operation.svg",
  "carousel-line": "/icons/carousel-line.svg",
  "carousel-dot": "/icons/carousel-dot.svg",
  "analysis-sql": "/icons/analysis-sql.svg",
  "analysis-session": "/icons/analysis-session.svg",
  "session-property": "/icons/session-property.svg",
  "custom-metrics": "/icons/custom-metrics.svg",
  "advertising-indicators": "/icons/advertising-indicators.svg",
  "event-indicators": "/icons/event-indicators.svg",
  "ltv-indicators": "/icons/ltv-indicators.svg",
  "retention-indicators": "/icons/retention-indicators.svg",
  "attributable-event-indicators": "/icons/attributable-event-indicators.svg",
  "base-woodfish-index": "/icons/base-woodfish-index.svg",
  "index-of-orange-station-construction": "/icons/index-of-orange-station-construction.svg",
  "intelligent-outbound-call": "/icons/intelligent-outbound-call.svg",
  "vis-detail-number": "/icons/vis-detail-number.svg",
  "vis-detail-letter": "/icons/vis-detail-letter.svg",
  "vis-detail-time": "/icons/vis-detail-time.svg",
  "vis-computed-column": "/icons/vis-computed-column.svg",
  "reduced-time": "/icons/reduced-time.svg",
  "custom-number-vis": "/icons/custom-number-vis.svg",
  "custom-letter-vis": "/icons/custom-letter-vis.svg",
  "flow-canvas": "/icons/flow-canvas.svg",
  "enter-event-shunt": "/icons/enter-event-shunt.svg",
  "sending-speed": "/icons/sending-speed.svg",
  "detail-bool": "/icons/detail-bool.svg",
  "vis-detail-bool": "/icons/vis-detail-bool.svg",
  "channel-minor-default": "/icons/channel-minor-default.svg",
  "data-preparation": "/icons/data-preparation.svg",
  "data-preparation-complete": "/icons/data-preparation-complete.svg",
  "campaign": "/icons/campaign.svg",
  "marketing-strategy": "/icons/marketing-strategy.svg",
  "strategy-insights": "/icons/strategy-insights.svg",
  "strategy-prediction": "/icons/strategy-prediction.svg",
  "data-insights": "/icons/data-insights.svg",
  "chart-stacked-column": "/icons/chart-stacked-column.svg",
  "chart-column-line": "/icons/chart-column-line.svg",
  "split-testing": "/icons/split-testing.svg",
  "auto-reload": "/icons/auto-reload.svg",
  "variant": "/icons/variant.svg",
  "webhook-sms": "/icons/webhook-sms.svg",
  "webhook-push": "/icons/webhook-push.svg",
  "webhook-email": "/icons/webhook-email.svg",
  "webhook-whatsapp": "/icons/webhook-whatsapp.svg",
  "webhook-waihu": "/icons/webhook-waihu.svg",
  "webhook-benefits": "/icons/webhook-benefits.svg",
  "intelli-sending-time": "/icons/intelli-sending-time.svg",
  "intellicampaign-ai": "/icons/intellicampaign-ai.svg",
  "intellidata-property-ai": "/icons/intellidata-property-ai.svg",
  "intellitag-ai": "/icons/intellitag-ai.svg",
  "intellidata-search-ai": "/icons/intellidata-search-ai.svg",
  "intellianaylsis-ai": "/icons/intellianaylsis-ai.svg",
  "intellichannels": "/icons/intellichannels.svg",
  "intellipath": "/icons/intellipath.svg",
  "intelliuser-insights": "/icons/intelliuser-insights.svg",
  "intelli-memory": "/icons/intelli-memory.svg",
  "intelli-match": "/icons/intelli-match.svg",
  "skills": "/icons/skills.svg",
  "knowledgebase": "/icons/knowledgebase.svg",
  "token-details": "/icons/token-details.svg",
  "agent-atom": "/icons/agent-atom.svg",
  "machine-learning": "/icons/machine-learning.svg",
  "virtual-users": "/icons/virtual-users.svg",
  "terminal": "/icons/terminal.svg",
  "prompt": "/icons/prompt.svg",
  "intelli-copywriting": "/icons/intelli-copywriting.svg",
  "prompt-management": "/icons/prompt-management.svg",
  "add-prompt": "/icons/add-prompt.svg",
};

const FIGMA_ICON_META: Record<FigmaIconName, { figmaName: string; category: IconCategory; labelZh?: string }> = {
  "bold": { figmaName: "bold", category: "edit", labelZh: "加粗", },
  "strikethrough": { figmaName: "strikethrough", category: "edit", labelZh: "删除线", },
  "stroke-none": { figmaName: "stroke-none", category: "edit", labelZh: "无边框", },
  "stroke-solid": { figmaName: "stroke-solid", category: "edit", labelZh: "实线边框", },
  "stroke-dash": { figmaName: "stroke-dash", category: "edit", labelZh: "虚线边框", },
  "rich-text": { figmaName: "rich-text", category: "edit", labelZh: "富文本", },
  "align-top": { figmaName: "align-top", category: "edit", labelZh: "顶部对齐", },
  "align-horizontal-center": { figmaName: "align-horizontal-center", category: "edit", labelZh: "水平居中", },
  "align-bottom": { figmaName: "align-bottom", category: "edit", labelZh: "底部对齐", },
  "align-left": { figmaName: "align-left", category: "edit", labelZh: "左对齐", },
  "align-vertical-center": { figmaName: "align-vertical-center", category: "edit", labelZh: "垂直居中", },
  "align-right": { figmaName: "align-right", category: "edit", labelZh: "右对齐", },
  "distribute-horizontal-spacing": { figmaName: "distribute-horizontal-spacing", category: "edit", labelZh: "水平均匀分布", },
  "distribute-vertical-spacing": { figmaName: "distribute-vertical-spacing", category: "edit", labelZh: "垂直均匀分布", },
  "underline": { figmaName: "underline", category: "edit", labelZh: "下划线", },
  "text-align-left": { figmaName: "text-align-left", category: "edit", labelZh: "文本左对齐", },
  "text-align-right": { figmaName: "text-align-right", category: "edit", labelZh: "文本右对齐", },
  "text-align-center": { figmaName: "text-align-center", category: "edit", labelZh: "文本居中对齐", },
  "text-align-justify": { figmaName: "text-align-justify", category: "edit", labelZh: "文本两端对齐", },
  "italic": { figmaName: "italic", category: "edit", labelZh: "斜体", },
  "underline-dotted": { figmaName: "underline-dotted", category: "edit", labelZh: "点状下划线", },
  "underline-wavy": { figmaName: "underline-wavy", category: "edit", labelZh: "波浪下划线", },
  "overline": { figmaName: "overline", category: "edit", labelZh: "上划线", },
  "top-left-corner-rounded": { figmaName: "top-left-corner-rounded", category: "edit", labelZh: "左上圆角", },
  "top-right-corner-rounded": { figmaName: "top-right-corner-rounded", category: "edit", labelZh: "右上圆角", },
  "bottom-left-corner-rounded": { figmaName: "bottom-left-corner-rounded", category: "edit", labelZh: "左下圆角", },
  "bottom-right-corner-rounded": { figmaName: "bottom-right-corner-rounded", category: "edit", labelZh: "右下圆角", },
  "left-float": { figmaName: "left-float", category: "edit", labelZh: "左浮动", },
  "right-float": { figmaName: "right-float", category: "edit", labelZh: "右浮动", },
  "above-element": { figmaName: "above-element", category: "edit", labelZh: "元素上方", },
  "under-of-element": { figmaName: "under-of-element", category: "edit", labelZh: "元素下方", },
  "padding-left": { figmaName: "padding-left", category: "edit", labelZh: "左内边距", },
  "padding-top": { figmaName: "padding-top", category: "edit", labelZh: "上内边距", },
  "padding-bottom": { figmaName: "padding-bottom", category: "edit", labelZh: "下内边距", },
  "padding-right": { figmaName: "padding-right", category: "edit", labelZh: "右内边距", },
  "search": { figmaName: "search", category: "operational", labelZh: "搜索", },
  "recover": { figmaName: "recover", category: "operational", labelZh: "恢复", },
  "share": { figmaName: "share", category: "operational", labelZh: "分享", },
  "zoom-in": { figmaName: "zoom-in", category: "operational", labelZh: "放大", },
  "zoom-out": { figmaName: "zoom-out", category: "operational", labelZh: "缩小", },
  "drag-horizontal": { figmaName: "drag-horizontal", category: "operational", labelZh: "横向拖拽", },
  "drag-vertical": { figmaName: "drag-vertical", category: "operational", labelZh: "纵向拖拽", },
  "visible": { figmaName: "visible", category: "operational", labelZh: "显示", },
  "hiding": { figmaName: "hiding", category: "operational", labelZh: "隐藏", },
  "attachment": { figmaName: "attachment", category: "operational", labelZh: "附件", },
  "unpin": { figmaName: "unpin", category: "operational", labelZh: "取消固定", },
  "pin": { figmaName: "pin", category: "operational", labelZh: "固定", },
  "link": { figmaName: "link", category: "operational", labelZh: "链接", },
  "calendar": { figmaName: "calendar", category: "operational", labelZh: "日历", },
  "download": { figmaName: "download", category: "operational", labelZh: "下载", },
  "copy": { figmaName: "copy", category: "operational", labelZh: "复制", },
  "logout": { figmaName: "logout", category: "operational", labelZh: "退出登录", },
  "connect": { figmaName: "connect", category: "operational", labelZh: "连接", },
  "save": { figmaName: "save", category: "operational", labelZh: "保存", },
  "filter": { figmaName: "filter", category: "operational", labelZh: "筛选", },
  "upload": { figmaName: "upload", category: "operational", labelZh: "上传", },
  "power-off": { figmaName: "power-off", category: "operational", labelZh: "关闭电源", },
  "send": { figmaName: "send", category: "operational", labelZh: "发送", },
  "fit-screen": { figmaName: "fit-screen", category: "operational", labelZh: "适应屏幕", },
  "rename": { figmaName: "rename", category: "operational", labelZh: "重命名", },
  "delete": { figmaName: "delete", category: "operational", labelZh: "删除", },
  "lock": { figmaName: "lock", category: "operational", labelZh: "锁定", },
  "unlock": { figmaName: "unlock", category: "operational", labelZh: "解锁", },
  "setting": { figmaName: "setting", category: "operational", labelZh: "设置", },
  "edit": { figmaName: "edit", category: "operational", labelZh: "编辑", },
  "scan": { figmaName: "scan", category: "operational", labelZh: "扫描", },
  "add-chart": { figmaName: "add-chart", category: "operational", labelZh: "添加图表", },
  "mark-as-read": { figmaName: "mark-as-read", category: "operational", labelZh: "标记为已读", },
  "convert": { figmaName: "convert", category: "operational", labelZh: "转换", },
  "format": { figmaName: "format", category: "operational", labelZh: "格式化", },
  "execute": { figmaName: "execute", category: "operational", labelZh: "执行", },
  "collect": { figmaName: "collect", category: "operational", labelZh: "收藏", },
  "import": { figmaName: "import", category: "operational", labelZh: "导入", },
  "view": { figmaName: "view", category: "operational", labelZh: "查看", },
  "filter-image": { figmaName: "filter-image", category: "operational", labelZh: "图片筛选", },
  "custom-size": { figmaName: "custom-size", category: "operational", labelZh: "自定义尺寸", },
  "code": { figmaName: "code", category: "operational", labelZh: "代码", },
  "unfollow": { figmaName: "unfollow", category: "operational", labelZh: "取消关注", },
  "table-expand": { figmaName: "table-expand", category: "operational", labelZh: "表格展开", },
  "table-collapse": { figmaName: "table-collapse", category: "operational", labelZh: "表格收起", },
  "card-view": { figmaName: "card-view", category: "operational", labelZh: "卡片视图", },
  "freeze": { figmaName: "freeze", category: "operational", labelZh: "冻结", },
  "describe": { figmaName: "describe", category: "operational", labelZh: "描述", },
  "markers": { figmaName: "markers", category: "operational", labelZh: "标记", },
  "optimize": { figmaName: "optimize", category: "operational", labelZh: "优化", },
  "calendar-utc": { figmaName: "calendar-utc", category: "operational", labelZh: "UTC 日历", },
  "filter-group": { figmaName: "filter-group", category: "operational", labelZh: "筛选分组", },
  "input-text": { figmaName: "input-text", category: "operational", labelZh: "文本输入", },
  "expand": { figmaName: "expand", category: "operational", labelZh: "展开", },
  "collapse": { figmaName: "collapse", category: "operational", labelZh: "收起", },
  "newchat": { figmaName: "newchat", category: "operational", labelZh: "新建对话", },
  "stop": { figmaName: "stop", category: "operational", labelZh: "停止", },
  "maximize": { figmaName: "maximize", category: "operational", labelZh: "最大化", },
  "minimize": { figmaName: "minimize", category: "operational", labelZh: "最小化", },
  "thumbs-up": { figmaName: "thumbs-up", category: "operational", labelZh: "点赞", },
  "search-replace": { figmaName: "search-replace", category: "operational", labelZh: "查找替换", },
  "strategy-search": { figmaName: "strategy-search", category: "operational", labelZh: "策略搜索", },
  "newchat-2": { figmaName: "newchat", category: "operational", labelZh: "新建对话（第二样式）", },
  "linkto": { figmaName: "linkto", category: "operational", labelZh: "关联", },
  "pause": { figmaName: "pause", category: "operational", labelZh: "暂停", },
  "execute-now": { figmaName: "execute-now", category: "operational", labelZh: "立即执行", },
  "time": { figmaName: "time", category: "object", labelZh: "时间", },
  "mail": { figmaName: "mail", category: "object", labelZh: "邮件", },
  "money": { figmaName: "money", category: "object", labelZh: "金额", },
  "person": { figmaName: "person", category: "object", labelZh: "人员", },
  "folder": { figmaName: "folder", category: "object", labelZh: "文件夹", },
  "remark": { figmaName: "remark", category: "object", labelZh: "备注", },
  "setting-batch-permission": { figmaName: "setting-batch-permission", category: "object", labelZh: "批量权限设置", },
  "emoji": { figmaName: "emoji", category: "object", labelZh: "表情", },
  "pop": { figmaName: "pop", category: "object", labelZh: "弹出", },
  "page-navigation": { figmaName: "page-navigation", category: "object", labelZh: "页面导航", },
  "layer": { figmaName: "layer", category: "object", labelZh: "图层", },
  "page": { figmaName: "page", category: "object", labelZh: "页面", },
  "component": { figmaName: "component", category: "object", labelZh: "组件", },
  "web": { figmaName: "web", category: "object", labelZh: "网页", },
  "tablet": { figmaName: "tablet", category: "object", labelZh: "平板", },
  "home": { figmaName: "home", category: "object", labelZh: "首页", },
  "person-add": { figmaName: "person-add", category: "object", labelZh: "添加人员", },
  "text-type": { figmaName: "text-type", category: "object", labelZh: "文本类型", },
  "checkbox-small": { figmaName: "checkbox-small", category: "symbol", labelZh: "小复选框", },
  "check": { figmaName: "check", category: "symbol", labelZh: "勾选", },
  "close": { figmaName: "close", category: "symbol", labelZh: "关闭", },
  "help": { figmaName: "help", category: "symbol", labelZh: "帮助", },
  "info": { figmaName: "info", category: "symbol", labelZh: "信息", },
  "more": { figmaName: "more", category: "symbol", labelZh: "更多", },
  "loading": { figmaName: "loading", category: "symbol", labelZh: "加载中", },
  "man": { figmaName: "man", category: "symbol", labelZh: "男性", },
  "woman": { figmaName: "woman", category: "symbol", labelZh: "女性", },
  "q-r-code": { figmaName: "q-r-code", category: "symbol", labelZh: "二维码", },
  "checkbox-line": { figmaName: "checkbox-line", category: "symbol", labelZh: "复选框线框", },
  "icon-default": { figmaName: "icon-default", category: "symbol", labelZh: "默认图标", },
  "add": { figmaName: "add", category: "symbol", labelZh: "添加", },
  "vip": { figmaName: "vip", category: "symbol", labelZh: "会员", },
  "percentage": { figmaName: "percentage", category: "symbol", labelZh: "百分比", },
  "vs": { figmaName: "VS", category: "symbol", labelZh: "对比", },
  "identifying-code": { figmaName: "identifying-code", category: "symbol", labelZh: "验证码", },
  "editor-add": { figmaName: "editor-add", category: "symbol", labelZh: "编辑器加法", },
  "editor-minus": { figmaName: "editor-minus", category: "symbol", labelZh: "编辑器减法", },
  "editor-product-sign": { figmaName: "editor-product-sign", category: "symbol", labelZh: "编辑器乘法", },
  "editor-sign-of-division": { figmaName: "editor-sign-of-division", category: "symbol", labelZh: "编辑器除法", },
  "editor-parenthesis-left": { figmaName: "editor-parenthesis-left", category: "symbol", labelZh: "左括号", },
  "editor-parenthesis-right": { figmaName: "editor-parenthesis-right", category: "symbol", labelZh: "右括号", },
  "editor-square-brackets-left": { figmaName: "editor-square-brackets-left", category: "symbol", labelZh: "左方括号", },
  "editor-square-brackets-right": { figmaName: "editor-square-brackets-right", category: "symbol", labelZh: "右方括号", },
  "width": { figmaName: "width", category: "symbol", labelZh: "宽度", },
  "high": { figmaName: "high", category: "symbol", labelZh: "高度", },
  "up": { figmaName: "up", category: "direction", labelZh: "向上", },
  "down": { figmaName: "down", category: "direction", labelZh: "向下", },
  "left": { figmaName: "left", category: "direction", labelZh: "向左", },
  "right": { figmaName: "right", category: "direction", labelZh: "向右", },
  "to-top": { figmaName: "to-top", category: "direction", labelZh: "回到顶部", },
  "indent": { figmaName: "indent", category: "direction", labelZh: "增加缩进", },
  "outdent": { figmaName: "outdent", category: "direction", labelZh: "减少缩进", },
  "reload": { figmaName: "reload", category: "direction", labelZh: "刷新", },
  "arrow-doubule-left": { figmaName: "arrow-doubule_left", category: "direction", labelZh: "双向左箭头", },
  "arrow-doubule-right": { figmaName: "arrow-doubule_right", category: "direction", labelZh: "双向右箭头", },
  "indent-right": { figmaName: "indent-right", category: "direction", labelZh: "右侧增加缩进", },
  "outdent-right": { figmaName: "outdent-right", category: "direction", labelZh: "右侧减少缩进", },
  "z-to-a": { figmaName: "z-to-a", category: "direction", labelZh: "Z 到 A", },
  "a-to-z": { figmaName: "a-to-z", category: "direction", labelZh: "A 到 Z", },
  "number0-to-9": { figmaName: "number0-to-9", category: "direction", labelZh: "数字升序", },
  "number9-to-0": { figmaName: "number9-to-0", category: "direction", labelZh: "数字降序", },
  "revoke": { figmaName: "revoke", category: "direction", labelZh: "撤销", },
  "redo": { figmaName: "redo", category: "direction", labelZh: "重做", },
  "reverse-order": { figmaName: "reverse-order", category: "direction", labelZh: "倒序", },
  "positive-sequence": { figmaName: "positive-sequence", category: "direction", labelZh: "正序", },
  "sort-senior": { figmaName: "sort-senior", category: "direction", labelZh: "高级排序", },
  "top": { figmaName: "top", category: "direction", labelZh: "置顶", },
  "bottom": { figmaName: "bottom", category: "direction", labelZh: "置底", },
  "descendant": { figmaName: "descendant", category: "direction", labelZh: "子级", },
  "ascendant": { figmaName: "ascendant", category: "direction", labelZh: "父级", },
  "descendant-group": { figmaName: "descendant-group", category: "direction", labelZh: "子级分组", },
  "ascendant-group": { figmaName: "ascendant-group", category: "direction", labelZh: "父级分组", },
  "back-navigate": { figmaName: "back-navigate", category: "direction", labelZh: "返回上级", },
  "next-level": { figmaName: "next-level", category: "direction", labelZh: "下一级", },
  "up-one-level": { figmaName: "up-one-level", category: "direction", labelZh: "上一级", },
  "expand-and-collapse-arrow-left": { figmaName: "expand-and-collapse-arrow-left", category: "direction", labelZh: "左右展开收起箭头", },
  "expand-and-collapse-arrow-right": { figmaName: "expand-and-collapse-arrow-right", category: "direction", labelZh: "右侧展开收起箭头", },
  "arrow-right": { figmaName: "arrow-right", category: "direction", labelZh: "右箭头", },
  "time-picker-right": { figmaName: "time-picker-right", category: "direction", labelZh: "时间选择器向右", },
  "android": { figmaName: "android", category: "brand", labelZh: "Android", },
  "mini-program": { figmaName: "mini-program", category: "brand", labelZh: "小程序", },
  "wechat": { figmaName: "wechat", category: "brand", labelZh: "微信", },
  "app": { figmaName: "app", category: "brand", labelZh: "应用", },
  "html-5": { figmaName: "html-5", category: "brand", labelZh: "HTML5", },
  "js": { figmaName: "js", category: "brand", labelZh: "JavaScript", },
  "sql": { figmaName: "sql", category: "brand", labelZh: "SQL", },
  "java": { figmaName: "java", category: "brand", labelZh: "Java", },
  "wechat-work": { figmaName: "wechat-work", category: "brand", labelZh: "企业微信", },
  "line": { figmaName: "line", category: "brand", labelZh: "Line", },
  "alipay": { figmaName: "alipay", category: "brand", labelZh: "支付宝", },
  "whatsapp": { figmaName: "whatsapp", category: "brand", labelZh: "WhatsApp", },
  "chart-point": { figmaName: "chart-point", category: "chart", labelZh: "点图", },
  "chart-bar": { figmaName: "chart-bar", category: "chart", labelZh: "柱状图", },
  "chart-line": { figmaName: "chart-line", category: "chart", labelZh: "折线图", },
  "chart-grouped-bar": { figmaName: "chart-grouped-bar", category: "chart", labelZh: "分组柱状图", },
  "chart-histogram": { figmaName: "chart-histogram", category: "chart", labelZh: "直方图", },
  "tree-association-node": { figmaName: "tree-association-node", category: "chart", labelZh: "树关联节点", },
  "tree-single-node": { figmaName: "tree-single-node", category: "chart", labelZh: "树单节点", },
  "board-view": { figmaName: "board-view", category: "chart", labelZh: "看板视图", },
  "sheet": { figmaName: "sheet", category: "chart", labelZh: "表格视图", },
  "business-model": { figmaName: "business-model", category: "chart", labelZh: "业务模型", },
  "chart": { figmaName: "chart", category: "chart", labelZh: "图表", },
  "helpcenter": { figmaName: "helpcenter", category: "functional", labelZh: "帮助中心", },
  "notice": { figmaName: "notice", category: "functional", labelZh: "通知", },
  "sbp": { figmaName: "sbp", category: "functional", labelZh: "权限管理", },
  "workload-manager": { figmaName: "workload-manager", category: "functional", labelZh: "工作量管理", },
  "examine": { figmaName: "examine", category: "functional", labelZh: "审核", },
  "phone": { figmaName: "phone", category: "functional", labelZh: "电话", },
  "after-sale": { figmaName: "after-sale", category: "functional", labelZh: "售后", },
  "diagnostic-tool": { figmaName: "diagnostic-tool", category: "functional", labelZh: "诊断工具", },
  "language": { figmaName: "language", category: "functional", labelZh: "语言", },
  "personal": { figmaName: "personal", category: "functional", labelZh: "个人", },
  "personal-sensitive-information": { figmaName: "personal-sensitive-information", category: "functional", labelZh: "个人敏感信息", },
  "operation-log": { figmaName: "operation-log", category: "functional", labelZh: "操作日志", },
  "notification-center": { figmaName: "notification-center", category: "functional", labelZh: "通知中心", },
  "query-queue": { figmaName: "query-queue", category: "functional", labelZh: "查询队列", },
  "api-key": { figmaName: "api-key", category: "functional", labelZh: "API Key", },
  "csv": { figmaName: "csv", category: "file", labelZh: "CSV 文件", },
  "png": { figmaName: "png", category: "file", labelZh: "PNG 图片", },
  "pdf": { figmaName: "pdf", category: "file", labelZh: "PDF 文件", },
  "picture": { figmaName: "picture", category: "file", labelZh: "图片", },
  "file": { figmaName: "file", category: "file", labelZh: "文件", },
  "event": { figmaName: "event", category: "business", labelZh: "事件", },
  "event-propertie": { figmaName: "event-propertie", category: "business", labelZh: "事件属性", },
  "preset-property": { figmaName: "preset-property", category: "business", labelZh: "预置属性", },
  "tag": { figmaName: "tag", category: "business", labelZh: "标签", },
  "custom-property": { figmaName: "custom-property", category: "business", labelZh: "自定义属性", },
  "user-group": { figmaName: "user-group", category: "business", labelZh: "用户组", },
  "user-property": { figmaName: "user-property", category: "business", labelZh: "用户属性", },
  "all": { figmaName: "all", category: "business", labelZh: "全部", },
  "time-controller": { figmaName: "time-controller", category: "business", labelZh: "时间控制器", },
  "audience-judgment": { figmaName: "audience-judgment", category: "business", labelZh: "受众判断", },
  "audience-real-time": { figmaName: "audience-real-time", category: "business", labelZh: "实时受众", },
  "event-unfinished": { figmaName: "event-unfinished", category: "business", labelZh: "未完成事件", },
  "timed-single-entry": { figmaName: "timed-single-entry", category: "business", labelZh: "定时单次进入", },
  "timed-repeat-entry": { figmaName: "timed-repeat-entry", category: "business", labelZh: "定时重复进入", },
  "proportional-shunt": { figmaName: "proportional-shunt", category: "business", labelZh: "按比例分流", },
  "webhook": { figmaName: "webhook", category: "business", labelZh: "Webhook", },
  "audience-shunt": { figmaName: "audience-shunt", category: "business", labelZh: "受众分流", },
  "period-shunt": { figmaName: "period-shunt", category: "business", labelZh: "周期分流", },
  "event-shunt": { figmaName: "event-shunt", category: "business", labelZh: "事件分流", },
  "goal": { figmaName: "goal", category: "business", labelZh: "目标", },
  "archive": { figmaName: "archive", category: "business", labelZh: "归档", },
  "number": { figmaName: "number", category: "business", labelZh: "数字", },
  "bool": { figmaName: "bool", category: "business", labelZh: "布尔", },
  "string": { figmaName: "string", category: "business", labelZh: "字符串", },
  "list": { figmaName: "list", category: "business", labelZh: "列表", },
  "object-array": { figmaName: "object-array", category: "business", labelZh: "对象数组", },
  "datetime": { figmaName: "datetime", category: "business", labelZh: "日期时间", },
  "template-picture-and-text": { figmaName: "template-picture-and-text", category: "business", labelZh: "图文模板", },
  "template-multiple-pictures-and-text": { figmaName: "template-multiple-pictures-and-text", category: "business", labelZh: "多图文模板", },
  "template-hot-zone": { figmaName: "template-hot-zone", category: "business", labelZh: "热区模板", },
  "template-text": { figmaName: "template-text", category: "business", labelZh: "文本模板", },
  "template-custom": { figmaName: "template-custom", category: "business", labelZh: "自定义模板", },
  "template-picture": { figmaName: "template-picture", category: "business", labelZh: "图片模板", },
  "template-multigraph": { figmaName: "template-multigraph", category: "business", labelZh: "多图模板", },
  "key": { figmaName: "key", category: "business", labelZh: "键", },
  "relation": { figmaName: "relation", category: "business", labelZh: "关联", },
  "no-correlation": { figmaName: "no-correlation", category: "business", labelZh: "无关联", },
  "dimension": { figmaName: "dimension", category: "business", labelZh: "维度", },
  "membership": { figmaName: "membership", category: "business", labelZh: "成员关系", },
  "list-letter": { figmaName: "list-letter", category: "business", labelZh: "列表文本", },
  "detail-number": { figmaName: "detail-number", category: "business", labelZh: "明细数字", },
  "detail-letter": { figmaName: "detail-letter", category: "business", labelZh: "明细文本", },
  "detail-time": { figmaName: "detail-time", category: "business", labelZh: "明细时间", },
  "computed-column": { figmaName: "computed-column", category: "business", labelZh: "计算列", },
  "time-macro": { figmaName: "time-macro", category: "business", labelZh: "时间宏", },
  "mode-key": { figmaName: "mode-key", category: "business", labelZh: "键模式", },
  "mode-automatic": { figmaName: "mode-automatic", category: "business", labelZh: "自动模式", },
  "group-management": { figmaName: "group-management", category: "business", labelZh: "分组管理", },
  "filter-list": { figmaName: "filter-list", category: "business", labelZh: "筛选列表", },
  "template-operation": { figmaName: "template-operation", category: "business", labelZh: "模板操作", },
  "carousel-line": { figmaName: "carousel-line", category: "business", labelZh: "轮播线", },
  "carousel-dot": { figmaName: "carousel-dot", category: "business", labelZh: "轮播点", },
  "analysis-sql": { figmaName: "analysis-sql", category: "business", labelZh: "SQL 分析", },
  "analysis-session": { figmaName: "analysis-session", category: "business", labelZh: "会话分析", },
  "session-property": { figmaName: "session-property", category: "business", labelZh: "会话属性", },
  "custom-metrics": { figmaName: "custom-metrics", category: "business", labelZh: "自定义指标", },
  "advertising-indicators": { figmaName: "advertising-indicators", category: "business", labelZh: "广告指标", },
  "event-indicators": { figmaName: "event-indicators", category: "business", labelZh: "事件指标", },
  "ltv-indicators": { figmaName: "ltv-indicators", category: "business", labelZh: "LTV 指标", },
  "retention-indicators": { figmaName: "retention-indicators", category: "business", labelZh: "留存指标", },
  "attributable-event-indicators": { figmaName: "attributable-event-indicators", category: "business", labelZh: "归因事件指标", },
  "base-woodfish-index": { figmaName: "base-woodfish-index", category: "business", labelZh: "基础木鱼指标", },
  "index-of-orange-station-construction": { figmaName: "index-of-orange-station-construction", category: "business", labelZh: "橙站建设指标", },
  "intelligent-outbound-call": { figmaName: "intelligent-outbound-call", category: "business", labelZh: "智能外呼", },
  "vis-detail-number": { figmaName: "vis-detail-number", category: "business", labelZh: "可视化明细数字", },
  "vis-detail-letter": { figmaName: "vis-detail-letter", category: "business", labelZh: "可视化明细文本", },
  "vis-detail-time": { figmaName: "vis-detail-time", category: "business", labelZh: "可视化明细时间", },
  "vis-computed-column": { figmaName: "vis-computed-column", category: "business", labelZh: "可视化计算列", },
  "reduced-time": { figmaName: "reduced-time", category: "business", labelZh: "缩短时间", },
  "custom-number-vis": { figmaName: "custom-number-vis", category: "business", labelZh: "自定义数字可视化", },
  "custom-letter-vis": { figmaName: "custom-letter-vis", category: "business", labelZh: "自定义文本可视化", },
  "flow-canvas": { figmaName: "flow-canvas", category: "business", labelZh: "流程画布", },
  "enter-event-shunt": { figmaName: "enter-event-shunt", category: "business", labelZh: "进入事件分流", },
  "sending-speed": { figmaName: "Sending-speed", category: "business", labelZh: "发送速度", },
  "detail-bool": { figmaName: "detail-bool", category: "business", labelZh: "明细布尔", },
  "vis-detail-bool": { figmaName: "vis-detail-bool", category: "business", labelZh: "可视化明细布尔", },
  "channel-minor-default": { figmaName: "channel-minor-default", category: "business", labelZh: "渠道次级默认", },
  "data-preparation": { figmaName: "data-preparation", category: "business", labelZh: "数据准备", },
  "data-preparation-complete": { figmaName: "data-preparation-complete", category: "business", labelZh: "数据准备完成", },
  "campaign": { figmaName: "campaign", category: "business", labelZh: "营销活动", },
  "marketing-strategy": { figmaName: "marketing-strategy", category: "business", labelZh: "营销策略", },
  "strategy-insights": { figmaName: "strategy-insights", category: "business", labelZh: "策略洞察", },
  "strategy-prediction": { figmaName: "strategy-prediction", category: "business", labelZh: "策略预测", },
  "data-insights": { figmaName: "data-insights", category: "business", labelZh: "数据洞察", },
  "chart-stacked-column": { figmaName: "chart-stacked-column", category: "business", labelZh: "堆叠柱状图", },
  "chart-column-line": { figmaName: "chart-column-line", category: "business", labelZh: "柱线图", },
  "split-testing": { figmaName: "split-testing", category: "business", labelZh: "分流测试", },
  "auto-reload": { figmaName: "auto-reload", category: "business", labelZh: "自动刷新", },
  "variant": { figmaName: "variant", category: "business", labelZh: "变体", },
  "webhook-sms": { figmaName: "webhook-sms", category: "business", labelZh: "Webhook 短信", },
  "webhook-push": { figmaName: "webhook-push", category: "business", labelZh: "Webhook 推送", },
  "webhook-email": { figmaName: "webhook-email", category: "business", labelZh: "Webhook 邮件", },
  "webhook-whatsapp": { figmaName: "webhook-whatsapp", category: "business", labelZh: "Webhook WhatsApp", },
  "webhook-waihu": { figmaName: "webhook-waihu", category: "business", labelZh: "Webhook 外呼", },
  "webhook-benefits": { figmaName: "webhook-benefits", category: "business", labelZh: "Webhook 权益", },
  "intelli-sending-time": { figmaName: "intelli-sending-time", category: "business", labelZh: "智能发送时间", },
  "intellicampaign-ai": { figmaName: "intellicampaign-AI", category: "business", labelZh: "智能营销活动", },
  "intellidata-property-ai": { figmaName: "intellidata-property-AI", category: "business", labelZh: "智能数据属性", },
  "intellitag-ai": { figmaName: "intellitag-AI", category: "business", labelZh: "智能标签", },
  "intellidata-search-ai": { figmaName: "intellidata-search-AI", category: "business", labelZh: "智能数据搜索", },
  "intellianaylsis-ai": { figmaName: "intellianaylsis-AI", category: "business", labelZh: "智能分析", },
  "intellichannels": { figmaName: "intellichannels", category: "business", labelZh: "智能渠道", },
  "intellipath": { figmaName: "intellipath", category: "business", labelZh: "智能路径", },
  "intelliuser-insights": { figmaName: "intelliuser-insights", category: "business", labelZh: "智能用户洞察", },
  "intelli-memory": { figmaName: "intelli-memory", category: "business", labelZh: "智能记忆", },
  "intelli-match": { figmaName: "intelli-match", category: "business", labelZh: "智能匹配", },
  "skills": { figmaName: "skills", category: "business", labelZh: "技能", },
  "knowledgebase": { figmaName: "knowledgebase", category: "business", labelZh: "知识库", },
  "token-details": { figmaName: "token-details", category: "business", labelZh: "Token 详情", },
  "agent-atom": { figmaName: "agent-atom", category: "business", labelZh: "Agent 原子能力", },
  "machine-learning": { figmaName: "machine-learning", category: "business", labelZh: "机器学习", },
  "virtual-users": { figmaName: "virtual-users", category: "business", labelZh: "虚拟用户", },
  "terminal": { figmaName: "terminal", category: "business", labelZh: "终端", },
  "prompt": { figmaName: "Prompt", category: "business", labelZh: "Prompt", },
  "intelli-copywriting": { figmaName: "intelli-copywriting", category: "business", labelZh: "智能文案", },
  "prompt-management": { figmaName: "prompt-management", category: "business", labelZh: "Prompt 管理", },
  "add-prompt": { figmaName: "add-prompt", category: "business", labelZh: "添加 Prompt", },
};

function createFigmaSvgIcon(assetUrl: string): ComponentType<RegistryIconRenderProps> {
  return function FigmaSvgIcon({ size = 16, className, style, color = "currentColor" }) {
    return (
      <span
        className={className}
        style={{
          display: "inline-flex",
          width: size,
          height: size,
          lineHeight: 0,
          flexShrink: 0,
          backgroundColor: color,
          WebkitMaskImage: `url("${assetUrl}")`,
          maskImage: `url("${assetUrl}")`,
          WebkitMaskRepeat: "no-repeat",
          maskRepeat: "no-repeat",
          WebkitMaskPosition: "center",
          maskPosition: "center",
          WebkitMaskSize: "100% 100%",
          maskSize: "100% 100%",
          ...style,
        }}
        aria-hidden
      />
    );
  };
}

const FIGMA_ICON_COMPONENTS = Object.fromEntries(
  FIGMA_ICON_NAMES.map((name) => [name, createFigmaSvgIcon(FIGMA_ICON_ASSETS[name])]),
) as Record<FigmaIconName, ComponentType<RegistryIconRenderProps>>;

export const FIGMA_ICON_REGISTRY = Object.fromEntries(
  FIGMA_ICON_NAMES.map((name) => {
    const meta = FIGMA_ICON_META[name];
    return [
      name,
      {
        name,
        figmaName: meta.figmaName,
        sourceComponent: "FigmaSvgIcon",
        sourceFile: `public/icons/${name}.svg`,
        viewBox: "0 0 16 16",
        category: meta.category,
        labelZh: meta.labelZh,
        currentColor: true,
        dualTone: false,
        temporary: false,
        usageScenes: [],
        Component: FIGMA_ICON_COMPONENTS[name],
      },
    ];
  }),
) as unknown as Record<FigmaIconName, IconRegistryEntry>;
