import type { ComponentType } from "react";
import type { IconCategory, RegistryIconRenderProps } from "./types";
import type { IconRegistryEntry } from "./registry";
import { FILLED_ICON_NAMES, type FilledIconName } from "./filled-icon-names";

const FILLED_ICON_ASSETS: Record<FilledIconName, string> = {
  "view-single": "/icons/filled/view-single.svg",
  "view-double": "/icons/filled/view-double.svg",
  "collect": "/icons/filled/collect.svg",
  "like": "/icons/filled/like.svg",
  "thumbs-up": "/icons/filled/thumbs-up.svg",
  "visual-view": "/icons/filled/visual-view.svg",
  "markers": "/icons/filled/markers.svg",
  "feedback": "/icons/filled/feedback.svg",
  "help": "/icons/filled/help.svg",
  "info": "/icons/filled/info.svg",
  "complete": "/icons/filled/complete.svg",
  "warning": "/icons/filled/warning.svg",
  "error": "/icons/filled/error.svg",
  "close-circle": "/icons/filled/close-circle.svg",
  "add-bold": "/icons/filled/add-bold.svg",
  "fail": "/icons/filled/fail.svg",
  "authorized": "/icons/filled/authorized.svg",
  "add": "/icons/filled/add.svg",
  "up": "/icons/filled/up.svg",
  "down": "/icons/filled/down.svg",
  "left": "/icons/filled/left.svg",
  "right": "/icons/filled/right.svg",
  "sort-up": "/icons/filled/sort-up.svg",
  "sort-down": "/icons/filled/sort-down.svg",
  "up-number-input": "/icons/filled/up-number-input.svg",
  "down-number-input": "/icons/filled/down-number-input.svg",
  "up-mini": "/icons/filled/up-mini.svg",
  "down-mini": "/icons/filled/down-mini.svg",
  "rise": "/icons/filled/rise.svg",
  "decline": "/icons/filled/decline.svg",
  "arrow-right": "/icons/filled/arrow-right.svg",
  "apple-ios": "/icons/filled/apple-ios.svg",
  "windows": "/icons/filled/windows.svg",
  "operating-system": "/icons/filled/operating-system.svg",
  "mac-os": "/icons/filled/mac-os.svg",
  "android": "/icons/filled/android.svg",
  "harmony-os": "/icons/filled/harmony-os.svg",
  "stack-chart": "/icons/filled/stack-chart.svg",
  "chart-loop": "/icons/filled/chart-loop.svg",
  "chart-pie": "/icons/filled/chart-pie.svg",
  "product-navigation": "/icons/filled/product-navigation.svg",
  "announcement": "/icons/filled/announcement.svg",
  "control-group": "/icons/filled/control-group.svg",
  "file": "/icons/filled/file.svg",
  "database": "/icons/filled/database.svg",
  "data-connection": "/icons/filled/data-connection.svg",
  "table-database": "/icons/filled/table-database.svg",
  "table-excel": "/icons/filled/table-excel.svg",
  "analysis-event": "/icons/filled/analysis-event.svg",
  "analysis-funnel": "/icons/filled/analysis-funnel.svg",
  "analysis-retention": "/icons/filled/analysis-retention.svg",
  "analysis-distribution": "/icons/filled/analysis-distribution.svg",
  "analysis-interval": "/icons/filled/analysis-interval.svg",
  "analysis-user-path": "/icons/filled/analysis-user-path.svg",
  "analysis-ltv": "/icons/filled/analysis-ltv.svg",
  "analysis-attribution": "/icons/filled/analysis-attribution.svg",
  "analysis-web-page-thermal": "/icons/filled/analysis-web-page-thermal.svg",
  "analysis-app-click": "/icons/filled/analysis-app-click.svg",
  "analysis-session": "/icons/filled/analysis-session.svg",
  "portrait-user-group": "/icons/filled/portrait-user-group.svg",
  "analysis-property": "/icons/filled/analysis-property.svg",
  "query-custom": "/icons/filled/query-custom.svg",
  "analysis-customize-service": "/icons/filled/analysis-customize-service.svg",
  "overview": "/icons/filled/overview.svg",
  "bookmark": "/icons/filled/bookmark.svg",
  "analysis-intelligent-early-warning": "/icons/filled/analysis-intelligent-early-warning.svg",
  "user-profiling": "/icons/filled/user-profiling.svg",
  "rfm": "/icons/filled/rfm.svg",
  "data-table": "/icons/filled/data-table.svg",
  "unified-dimension-aggregation": "/icons/filled/unified-dimension-aggregation.svg",
  "splicing-model-horizontal": "/icons/filled/splicing-model-horizontal.svg",
  "splicing-model-vertical": "/icons/filled/splicing-model-vertical.svg",
  "datatable": "/icons/filled/datatable.svg",
  "user-behavior-sequence": "/icons/filled/user-behavior-sequence.svg",
};

const FILLED_ICON_META: Record<FilledIconName, { figmaName: string; category: IconCategory; labelZh?: string }> = {
  "view-single": { figmaName: "view-single", category: "operational", labelZh: "单视图" },
  "view-double": { figmaName: "view-double", category: "operational", labelZh: "双视图" },
  "collect": { figmaName: "collect", category: "operational", labelZh: "收藏" },
  "like": { figmaName: "like", category: "operational", labelZh: "喜欢" },
  "thumbs-up": { figmaName: "thumbs-up", category: "operational", labelZh: "点赞" },
  "visual-view": { figmaName: "visual-view", category: "operational", labelZh: "可视化查看" },
  "markers": { figmaName: "markers", category: "operational", labelZh: "标记" },
  "feedback": { figmaName: "feedback", category: "object", labelZh: "反馈" },
  "help": { figmaName: "help", category: "symbol", labelZh: "帮助" },
  "info": { figmaName: "info", category: "symbol", labelZh: "信息" },
  "complete": { figmaName: "complete", category: "symbol", labelZh: "完成" },
  "warning": { figmaName: "warning", category: "symbol", labelZh: "提醒" },
  "error": { figmaName: "error", category: "symbol", labelZh: "错误" },
  "close-circle": { figmaName: "close-circle", category: "symbol", labelZh: "关闭" },
  "add-bold": { figmaName: "add-bold", category: "symbol", labelZh: "加粗添加" },
  "fail": { figmaName: "fail", category: "symbol", labelZh: "失败" },
  "authorized": { figmaName: "authorized", category: "symbol", labelZh: "已授权" },
  "add": { figmaName: "add", category: "symbol", labelZh: "添加" },
  "up": { figmaName: "up", category: "direction", labelZh: "向上" },
  "down": { figmaName: "down", category: "direction", labelZh: "向下" },
  "left": { figmaName: "left", category: "direction", labelZh: "向左" },
  "right": { figmaName: "right", category: "direction", labelZh: "向右" },
  "sort-up": { figmaName: "sort-up", category: "direction", labelZh: "升序" },
  "sort-down": { figmaName: "sort-down", category: "direction", labelZh: "降序" },
  "up-number-input": { figmaName: "up-number-input", category: "direction", labelZh: "数字输入增加" },
  "down-number-input": { figmaName: "down-number-input", category: "direction", labelZh: "数字输入减少" },
  "up-mini": { figmaName: "up-mini", category: "direction", labelZh: "小号向上" },
  "down-mini": { figmaName: "down-mini", category: "direction", labelZh: "小号向下" },
  "rise": { figmaName: "rise", category: "direction", labelZh: "上涨" },
  "decline": { figmaName: "decline", category: "direction", labelZh: "下跌" },
  "arrow-right": { figmaName: "arrow-right", category: "direction", labelZh: "向右箭头" },
  "apple-ios": { figmaName: "apple-ios", category: "brand", labelZh: "Apple iOS" },
  "windows": { figmaName: "windows", category: "brand", labelZh: "Windows" },
  "operating-system": { figmaName: "operating-system", category: "brand", labelZh: "操作系统" },
  "mac-os": { figmaName: "mac-os", category: "brand", labelZh: "macOS" },
  "android": { figmaName: "android", category: "brand", labelZh: "Android" },
  "harmony-os": { figmaName: "harmony-os", category: "brand", labelZh: "HarmonyOS" },
  "stack-chart": { figmaName: "stack-chart", category: "chart", labelZh: "堆叠图表" },
  "chart-loop": { figmaName: "chart-loop", category: "chart", labelZh: "环形图表" },
  "chart-pie": { figmaName: "chart-pie", category: "chart", labelZh: "饼图" },
  "product-navigation": { figmaName: "product-navigation", category: "functional", labelZh: "产品导航" },
  "announcement": { figmaName: "announcement", category: "functional", labelZh: "公告" },
  "control-group": { figmaName: "control-group", category: "functional", labelZh: "控制组" },
  "file": { figmaName: "file", category: "file", labelZh: "文件" },
  "database": { figmaName: "database", category: "file", labelZh: "数据库" },
  "data-connection": { figmaName: "data-connection", category: "file", labelZh: "数据连接" },
  "table-database": { figmaName: "table-database", category: "file", labelZh: "数据库表" },
  "table-excel": { figmaName: "table-excel", category: "file", labelZh: "Excel 表格" },
  "analysis-event": { figmaName: "analysis-event", category: "business", labelZh: "事件分析" },
  "analysis-funnel": { figmaName: "analysis-funnel", category: "business", labelZh: "漏斗分析" },
  "analysis-retention": { figmaName: "analysis-retention", category: "business", labelZh: "留存分析" },
  "analysis-distribution": { figmaName: "analysis-distribution", category: "business", labelZh: "分布分析" },
  "analysis-interval": { figmaName: "analysis-interval", category: "business", labelZh: "间隔分析" },
  "analysis-user-path": { figmaName: "analysis-user-path", category: "business", labelZh: "用户路径分析" },
  "analysis-ltv": { figmaName: "analysis-ltv", category: "business", labelZh: "LTV 分析" },
  "analysis-attribution": { figmaName: "analysis-attribution", category: "business", labelZh: "归因分析" },
  "analysis-web-page-thermal": { figmaName: "analysis-web-page-thermal", category: "business", labelZh: "网页热力分析" },
  "analysis-app-click": { figmaName: "analysis-app-click", category: "business", labelZh: "应用点击分析" },
  "analysis-session": { figmaName: "analysis-session", category: "business", labelZh: "会话分析" },
  "portrait-user-group": { figmaName: "portrait-user-group", category: "business", labelZh: "用户群画像" },
  "analysis-property": { figmaName: "analysis-property", category: "business", labelZh: "属性分析" },
  "query-custom": { figmaName: "query-custom", category: "business", labelZh: "自定义查询" },
  "analysis-customize-service": { figmaName: "analysis-customize-service", category: "business", labelZh: "自定义服务分析" },
  "overview": { figmaName: "overview", category: "business", labelZh: "概览" },
  "bookmark": { figmaName: "bookmark", category: "business", labelZh: "书签" },
  "analysis-intelligent-early-warning": { figmaName: "analysis-intelligent-early-warning", category: "business", labelZh: "智能预警分析" },
  "user-profiling": { figmaName: "user-profiling", category: "business", labelZh: "用户画像" },
  "rfm": { figmaName: "rfm", category: "business", labelZh: "RFM 分析" },
  "data-table": { figmaName: "data-table", category: "business", labelZh: "数据表" },
  "unified-dimension-aggregation": { figmaName: "unified-dimension-aggregation", category: "business", labelZh: "统一维度聚合" },
  "splicing-model-horizontal": { figmaName: "splicing-model-horizontal", category: "business", labelZh: "横向拼接模型" },
  "splicing-model-vertical": { figmaName: "splicing-model-vertical", category: "business", labelZh: "纵向拼接模型" },
  "datatable": { figmaName: "datatable", category: "business", labelZh: "数据表格" },
  "user-behavior-sequence": { figmaName: "user-behavior-sequence", category: "business", labelZh: "用户行为序列" },
};

function createFilledFigmaIcon(assetUrl: string): ComponentType<RegistryIconRenderProps> {
  return function FilledFigmaIcon({ size = 16, className, style, color = "currentColor" }) {
    return (
      <span
        className={className}
        style={{
          display: "inline-flex",
          width: size,
          height: size,
          lineHeight: 0,
          flexShrink: 0,
          backgroundColor: color,
          WebkitMaskImage: `url("${assetUrl}")`,
          maskImage: `url("${assetUrl}")`,
          WebkitMaskRepeat: "no-repeat",
          maskRepeat: "no-repeat",
          WebkitMaskPosition: "center",
          maskPosition: "center",
          WebkitMaskSize: "100% 100%",
          maskSize: "100% 100%",
          ...style,
        }}
        aria-hidden
      />
    );
  };
}

const FILLED_ICON_COMPONENTS = Object.fromEntries(
  FILLED_ICON_NAMES.map((name) => [name, createFilledFigmaIcon(FILLED_ICON_ASSETS[name])]),
) as Record<FilledIconName, ComponentType<RegistryIconRenderProps>>;

export const FIGMA_FILLED_ICON_REGISTRY = Object.fromEntries(
  FILLED_ICON_NAMES.map((name) => {
    const meta = FILLED_ICON_META[name];
    return [
      name,
      {
        name,
        figmaName: meta.figmaName,
        sourceComponent: "FilledFigmaIcon",
        sourceFile: `public/icons/filled/${name}.svg`,
        viewBox: "0 0 16 16",
        category: meta.category,
        labelZh: meta.labelZh,
        currentColor: true,
        dualTone: false,
        temporary: false,
        usageScenes: [],
        Component: FILLED_ICON_COMPONENTS[name],
      },
    ];
  }),
) as unknown as Record<FilledIconName, IconRegistryEntry>;
