import type { ComponentType } from "react";
import {
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  CheckboxCheckIcon,
  CheckIcon,
  CloseCircleIcon,
  CloseIcon,
  DragVerticalIcon,
  DoubleChevronLeftIcon,
  DoubleChevronRightIcon,
  EditorAddIcon,
  ErrorDiamondIcon,
  FeedbackCompleteIcon,
  FeedbackErrorIcon,
  FeedbackInfoIcon,
  FeedbackWarningIcon,
  FilterChevronDownIcon,
  FilterChevronUpIcon,
  HelpIcon,
  IconDefaultIcon,
  MoreIcon,
  NavDownIcon,
  NavExamineIcon,
  NavHelpcenterIcon,
  NavLanguageIcon,
  NavNoticeIcon,
  NavPlatformIcon,
  NavProductNavigationIcon,
  SideNavCollapseIcon,
  SideNavDownIcon,
  SideNavExpandIcon,
  SideNavLinkIcon,
  SideNavPinIcon,
  SideNavUnpinIcon,
  SideNavUpIcon,
  SdgDataQualityIcon,
  SaBehaviorAnalysisSideNavIcon,
  SaBusinessAnalysisSideNavIcon,
  SaOtherSideNavIcon,
  SaUserAnalysisSideNavIcon,
  SdhDataModelUserEntityManageIcon,
  SdhEntityConfIcon,
  SdhWarehousingGeneralDataIngestionIcon,
  SdiWarehousingDataIngestionIcon,
  SbpMemberSideNavIcon,
  SbpRoleSideNavIcon,
  SbpSettingSideNavIcon,
  NavWorkloadManagerIcon,
  ReloadIcon,
  RenameIcon,
  SelectCheckIcon,
  SettingIcon,
  StepperDownIcon,
  StepperUpIcon,
  WarningFilledIcon,
} from "../../ui/FieldIcons";
import {
  Default2SideNavIcon,
  Default3SideNavIcon,
  DefaultSideNavIcon,
  SaDashboardSideNavIcon,
  SaDatasetSideNavIcon,
  SaDebuggingEquipmentSideNavIcon,
  SaManagementSideNavIcon,
  SaReportSideNavIcon,
  SaTestCengSideNavIcon,
  SaTestIndicatorSideNavIcon,
  SaTestListSideNavIcon,
  SatAdAssetsSideNavIcon,
  SatAdManagementConfigSideNavIcon,
  SatAdPromoteSideNavIcon,
  SatDashboardSideNavIcon,
  SatReportSideNavIcon,
  SatToolsSideNavIcon,
  SbpApprovalDataManageSideNavIcon,
  SbpApprovalFinishSideNavIcon,
  SbpApprovalInitiateSideNavIcon,
  SbpApprovalSettingSideNavIcon,
  SbpApprovalSwitchSideNavIcon,
  SbpApprovalTodoSideNavIcon,
  SbpEmailManageSideNavIcon,
  SbpOperationLogSideNavIcon,
  SbpOverviewSideNavIcon,
  SbpSecuritySettingSideNavIcon,
  SbpWorkloadBizAssetsSideNavIcon,
  SbpWorkloadQueryTaskSideNavIcon,
  ScmsCenterSideNavIcon,
  ScmsSettingSideNavIcon,
  ScrmCommunityOperationSideNavIcon,
  ScrmCustomerManagementSideNavIcon,
  ScrmMarketingCustomerSideNavIcon,
  ScrmMarketingTasksSideNavIcon,
  ScrmMaterialManagementSideNavIcon,
  ScrmWorkNotifySideNavIcon,
  SdgWarehousingSideNavIcon,
  SdhDataModelTableManageSideNavIcon,
  SfActiveMarketingSideNavIcon,
  SfSceneSideNavIcon,
  SfSectionSideNavIcon,
  SfWechatSideNavIcon,
} from "../../ui/SideNavProductIcons";
import { SearchIcon } from "../../ui/SearchIcon";
import { FIGMA_ICON_REGISTRY } from "./figma-icons";
import { FIGMA_FILLED_ICON_REGISTRY } from "./filled-icons";
import { COLORFUL_ICON_REGISTRY } from "./colorful-icons";
import { COLORFUL_ICON_NAMES, type ColorfulIconName } from "./colorful-icon-names";
import type { FilledIconName } from "./filled-icon-names";
import type { IconAssetMeta, IconName, IconVariant, RegistryIconRenderProps } from "./types";

export interface IconRegistryEntry extends IconAssetMeta {
  Component: ComponentType<RegistryIconRenderProps>;
}

const LEGACY_ICON_REGISTRY: Record<string, IconRegistryEntry> = {
  "error-diamond": {
    name: "error-diamond",
    sourceComponent: "ErrorDiamondIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "status",
    labelZh: "报错菱形",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Input / TextArea / InputNumber 表单警告",
        typicalSizes: [14, 16],
        typicalColorRoles: ["warning", "inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: ErrorDiamondIcon,
  },
  "feedback-info": {
    name: "feedback-info",
    sourceComponent: "FeedbackInfoIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "status",
    labelZh: "反馈状态-信息",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Message / Alert 常规反馈图标",
        typicalSizes: [16],
        typicalColorRoles: ["link", "inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: FeedbackInfoIcon,
  },
  "feedback-complete": {
    name: "feedback-complete",
    sourceComponent: "FeedbackCompleteIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "status",
    labelZh: "反馈状态-完成",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Message / Alert 成功反馈图标",
        typicalSizes: [16],
        typicalColorRoles: ["functional", "inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: FeedbackCompleteIcon,
  },
  "feedback-warning": {
    name: "feedback-warning",
    sourceComponent: "FeedbackWarningIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "status",
    labelZh: "反馈状态-提醒",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Message / Alert 提醒反馈图标",
        typicalSizes: [16],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: FeedbackWarningIcon,
  },
  "feedback-error": {
    name: "feedback-error",
    sourceComponent: "FeedbackErrorIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "status",
    labelZh: "反馈状态-报错",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Form / Message / Alert 报错或警告红反馈图标",
        typicalSizes: [16],
        typicalColorRoles: ["warning", "inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: FeedbackErrorIcon,
  },
  "filter-chevron-down": {
    name: "filter-chevron-down",
    sourceComponent: "FilterChevronDownIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "component-internal",
    labelZh: "筛选区展开线性下箭头",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "复合表格筛选区「展开」按钮",
        typicalSizes: [16],
        typicalColorRoles: ["link", "inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: FilterChevronDownIcon,
  },
  "filter-chevron-up": {
    name: "filter-chevron-up",
    sourceComponent: "FilterChevronUpIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "component-internal",
    labelZh: "筛选区收起线性上箭头",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "复合表格筛选区「收起」按钮",
        typicalSizes: [16],
        typicalColorRoles: ["link", "inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: FilterChevronUpIcon,
  },
  help: {
    name: "help",
    sourceComponent: "HelpIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "input-assist",
    labelZh: "帮助说明",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [
      {
        scene: "Form / Radio / Checkbox 标题或选项旁的帮助说明入口",
        typicalSizes: [16],
        typicalColorRoles: ["subtle", "inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: HelpIcon,
  },
  "icon-default": {
    name: "icon-default",
    sourceComponent: "IconDefaultIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "operational",
    labelZh: "默认示例图标",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [
      {
        scene: "Button showcase 示例图标",
        typicalSizes: [16],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: IconDefaultIcon,
  },
  "select-check": {
    name: "select-check",
    sourceComponent: "SelectCheckIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "status",
    labelZh: "下拉已选勾选",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Select Dropdown 已选中勾选",
        typicalSizes: [16],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: SelectCheckIcon,
  },
  "checkbox-check": {
    name: "checkbox-check",
    sourceComponent: "CheckboxCheckIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "component-internal",
    labelZh: "复选框选中勾选",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Checkbox 选中态内部对勾",
        typicalSizes: [16],
        typicalColorRoles: ["inverse", "inherit"],
        reusableAtOtherSizes: false,
      },
    ],
    Component: CheckboxCheckIcon,
  },
  "stepper-up": {
    name: "stepper-up",
    sourceComponent: "StepperUpIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 10 10",
    category: "component-internal",
    labelZh: "数字步进器上箭头",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "InputNumber stepper 上箭头",
        typicalSizes: [10],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: false,
      },
    ],
    Component: StepperUpIcon,
  },
  "stepper-down": {
    name: "stepper-down",
    sourceComponent: "StepperDownIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 10 10",
    category: "component-internal",
    labelZh: "数字步进器下箭头",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "InputNumber stepper 下箭头",
        typicalSizes: [10],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: false,
      },
    ],
    Component: StepperDownIcon,
  },
  "chevron-left": {
    name: "chevron-left",
    sourceComponent: "ChevronLeftIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "navigation",
    labelZh: "向左箭头",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Minimal Search 返回箭头",
        typicalSizes: [16],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: true,
      },
      {
        scene: "Pagination 上一页翻页按钮",
        typicalSizes: [16],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: ChevronLeftIcon,
  },
  "chevron-right": {
    name: "chevron-right",
    sourceComponent: "ChevronRightIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "navigation",
    labelZh: "向右箭头",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Pagination 下一页翻页按钮",
        typicalSizes: [16],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: ChevronRightIcon,
  },
  "double-chevron-left": {
    name: "double-chevron-left",
    sourceComponent: "DoubleChevronLeftIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "navigation",
    labelZh: "双左箭头",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Pagination 省略号悬停后向前 5 页",
        typicalSizes: [16],
        typicalColorRoles: ["link", "inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: DoubleChevronLeftIcon,
  },
  "double-chevron-right": {
    name: "double-chevron-right",
    sourceComponent: "DoubleChevronRightIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "navigation",
    labelZh: "双右箭头",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Pagination 省略号悬停后向后 5 页",
        typicalSizes: [16],
        typicalColorRoles: ["link", "inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: DoubleChevronRightIcon,
  },
  "chevron-down": {
    name: "chevron-down",
    sourceComponent: "ChevronDownIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "navigation",
    labelZh: "向下箭头",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Select 触发框 / Dropdown / Button 下箭头",
        typicalSizes: [16],
        typicalColorRoles: ["subtle", "inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: ChevronDownIcon,
  },
  "chevron-up": {
    name: "chevron-up",
    sourceComponent: "ChevronUpIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "navigation",
    labelZh: "向上箭头",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Select / Dropdown / Button 上箭头",
        typicalSizes: [16],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: ChevronUpIcon,
  },
  "close": {
    name: "close",
    sourceComponent: "CloseIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "operational",
    labelZh: "关闭叉子",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Tag / Message / Alert 关闭",
        typicalSizes: [12, 14, 16],
        typicalColorRoles: ["subtle", "warning", "inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: CloseIcon,
  },
  "close-circle": {
    name: "close-circle",
    sourceComponent: "CloseCircleIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "operational",
    labelZh: "圆形清空",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [
      {
        scene: "Input / Select / Search allowClear 清空",
        typicalSizes: [16],
        typicalColorRoles: ["subtle", "inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: CloseCircleIcon,
  },
  check: {
    name: "check",
    sourceComponent: "CheckIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "status",
    labelZh: "对勾",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Card / Checkbox 已选中勾选",
        typicalSizes: [16],
        typicalColorRoles: ["inverse", "inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: CheckIcon,
  },
  rename: {
    name: "rename",
    sourceComponent: "RenameIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "operational",
    labelZh: "重命名铅笔",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [
      {
        scene: "Card 标题区重命名",
        typicalSizes: [16],
        typicalColorRoles: ["subtle", "inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: RenameIcon,
  },
  "warning-filled": {
    name: "warning-filled",
    sourceComponent: "WarningFilledIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "status",
    labelZh: "警告面性",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Card 框外警告信息",
        typicalSizes: [14, 16],
        typicalColorRoles: ["warning"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: WarningFilledIcon,
  },
  "editor-add": {
    name: "editor-add",
    sourceComponent: "EditorAddIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "operational",
    labelZh: "编辑器加号",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "新建 / 添加按钮",
        typicalSizes: [16],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: EditorAddIcon,
  },
  "drag-vertical": {
    name: "drag-vertical",
    sourceComponent: "DragVerticalIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "operational",
    labelZh: "纵向拖拽",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Card 标题区拖拽把手",
        typicalSizes: [16],
        typicalColorRoles: ["subtle", "inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: DragVerticalIcon,
  },
  more: {
    name: "more",
    sourceComponent: "MoreIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "operational",
    labelZh: "更多",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "更多按钮",
        typicalSizes: [16],
        typicalColorRoles: ["subtle", "inherit"],
        reusableAtOtherSizes: true,
      },
      {
        scene: "Pagination 默认省略号",
        typicalSizes: [16],
        typicalColorRoles: ["default", "inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: MoreIcon,
  },
  search: {
    name: "search",
    sourceComponent: "SearchIcon",
    sourceFile: "src/ui/SearchIcon.tsx",
    viewBox: "0 0 16 16",
    category: "input-assist",
    labelZh: "搜索",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Search / Input 搜索前缀、搜索按钮",
        typicalSizes: [16],
        typicalColorRoles: ["subtle", "inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: SearchIcon,
  },
  "nav-helpcenter": {
    name: "nav-helpcenter",
    sourceComponent: "NavHelpcenterIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "navigation",
    labelZh: "顶部导航帮助中心",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [
      {
        scene: "Top Navigation 右上角工具区 / 帮助中心",
        typicalSizes: [16],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: NavHelpcenterIcon,
  },
  "nav-notice": {
    name: "nav-notice",
    sourceComponent: "NavNoticeIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "navigation",
    labelZh: "顶部导航通知",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [
      {
        scene: "Top Navigation 右上角工具区 / 通知",
        typicalSizes: [16],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: NavNoticeIcon,
  },
  "nav-platform": {
    name: "nav-platform",
    sourceComponent: "NavPlatformIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "navigation",
    labelZh: "顶部导航平台",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [
      {
        scene: "Top Navigation 右上角工具区 / 平台",
        typicalSizes: [16],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: NavPlatformIcon,
  },
  "nav-workload-manager": {
    name: "nav-workload-manager",
    sourceComponent: "NavWorkloadManagerIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "navigation",
    labelZh: "顶部导航资源管理",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [
      {
        scene: "Top Navigation 右上角工具区 / 资源管理",
        typicalSizes: [16],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: NavWorkloadManagerIcon,
  },
  "nav-examine": {
    name: "nav-examine",
    sourceComponent: "NavExamineIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "navigation",
    labelZh: "顶部导航审批",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [
      {
        scene: "Top Navigation 右上角工具区 / 审批",
        typicalSizes: [16],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: NavExamineIcon,
  },
  "nav-language": {
    name: "nav-language",
    sourceComponent: "NavLanguageIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "navigation",
    labelZh: "顶部导航语言",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [
      {
        scene: "Top Navigation 右上角工具区 / 语言",
        typicalSizes: [16],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: NavLanguageIcon,
  },
  "nav-product-navigation": {
    name: "nav-product-navigation",
    sourceComponent: "NavProductNavigationIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "navigation",
    labelZh: "顶部导航产品切换",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Top Navigation 下导航功能入口 / 产品切换",
        typicalSizes: [16],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: NavProductNavigationIcon,
  },
  "nav-down": {
    name: "nav-down",
    sourceComponent: "NavDownIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "navigation",
    labelZh: "顶部导航向下箭头",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Top Navigation 项目切换 / 导航项展开",
        typicalSizes: [16],
        typicalColorRoles: ["inherit"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: NavDownIcon,
  },
  "side-nav-down": {
    name: "side-nav-down",
    sourceComponent: "SideNavDownIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 14 14",
    category: "navigation",
    labelZh: "侧导航二级模块展开",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 二级模块收起", typicalSizes: [14], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SideNavDownIcon,
  },
  "side-nav-up": {
    name: "side-nav-up",
    sourceComponent: "SideNavUpIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 14 14",
    category: "navigation",
    labelZh: "侧导航二级模块收起",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 二级模块展开", typicalSizes: [14], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SideNavUpIcon,
  },
  "side-nav-link": {
    name: "side-nav-link",
    sourceComponent: "SideNavLinkIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "navigation",
    labelZh: "侧导航更多推荐链接",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 更多推荐", typicalSizes: [16], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SideNavLinkIcon,
  },
  "side-nav-expand": {
    name: "side-nav-expand",
    sourceComponent: "SideNavExpandIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 18 18",
    category: "navigation",
    labelZh: "侧导航紧凑态展开",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 紧凑态展开", typicalSizes: [18], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SideNavExpandIcon,
  },
  "side-nav-collapse": {
    name: "side-nav-collapse",
    sourceComponent: "SideNavCollapseIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 18 18",
    category: "navigation",
    labelZh: "侧导航锁定后收起",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 锁定态收起", typicalSizes: [18], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SideNavCollapseIcon,
  },
  "side-nav-unpin": {
    name: "side-nav-unpin",
    sourceComponent: "SideNavUnpinIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "navigation",
    labelZh: "侧导航锁定入口",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 悬停展开后锁定", typicalSizes: [16], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SideNavUnpinIcon,
  },
  "side-nav-pin": {
    name: "side-nav-pin",
    sourceComponent: "SideNavPinIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 12.2838 12.2838",
    category: "navigation",
    labelZh: "侧导航锁定",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 锁定图标状态", typicalSizes: [16], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SideNavPinIcon,
  },
  "sdi-warehousing-data-ingestion": {
    name: "sdi-warehousing-data-ingestion",
    sourceComponent: "SdiWarehousingDataIngestionIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 20 20",
    category: "navigation",
    labelZh: "侧导航埋点数据接入",
    figmaName: "sdi-warehousing-data-ingestion",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 二级有图标 / 埋点数据接入", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SdiWarehousingDataIngestionIcon,
  },
  "sdh-warehousing-general-data-ingestion": {
    name: "sdh-warehousing-general-data-ingestion",
    sourceComponent: "SdhWarehousingGeneralDataIngestionIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 20 20",
    category: "navigation",
    labelZh: "侧导航通用数据接入",
    figmaName: "sdh-warehousing-general-data-ingestion",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 二级有图标 / 通用数据接入", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SdhWarehousingGeneralDataIngestionIcon,
  },
  "sdh-data-model-user-entity-manage": {
    name: "sdh-data-model-user-entity-manage",
    sourceComponent: "SdhDataModelUserEntityManageIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 20 20",
    category: "navigation",
    labelZh: "侧导航元数据管理",
    figmaName: "sdh-data-model-user-entity-manage",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 二级有图标 / 元数据管理", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SdhDataModelUserEntityManageIcon,
  },
  "sdh-entity-conf": {
    name: "sdh-entity-conf",
    sourceComponent: "SdhEntityConfIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 20 20",
    category: "navigation",
    labelZh: "侧导航实体配置",
    figmaName: "sdh-entity-conf",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 二级有图标 / 实体配置", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SdhEntityConfIcon,
  },
  "sdg-dataquality": {
    name: "sdg-dataquality",
    sourceComponent: "SdgDataQualityIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 20 20",
    category: "navigation",
    labelZh: "侧导航数据质量",
    figmaName: "sdg-dataquality",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 二级有图标 / 数据质量", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SdgDataQualityIcon,
  },
  "sa-behavioranalysis": {
    name: "sa-behavioranalysis",
    sourceComponent: "SaBehaviorAnalysisSideNavIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 20 20",
    category: "navigation",
    labelZh: "侧导航分析 / 行为分析",
    figmaName: "sa-behavioranalysis",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 分析专属虚拟二级 / 行为分析", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SaBehaviorAnalysisSideNavIcon,
  },
  "sa-useranalysis": {
    name: "sa-useranalysis",
    sourceComponent: "SaUserAnalysisSideNavIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 20 20",
    category: "navigation",
    labelZh: "侧导航分析 / 用户分析",
    figmaName: "sa-useranalysis",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 分析专属虚拟二级 / 用户分析", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SaUserAnalysisSideNavIcon,
  },
  "sa-businessanalysis": {
    name: "sa-businessanalysis",
    sourceComponent: "SaBusinessAnalysisSideNavIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 20 20",
    category: "navigation",
    labelZh: "侧导航分析 / 经营分析",
    figmaName: "sa-businessanalysis",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 分析专属虚拟二级 / 经营分析", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SaBusinessAnalysisSideNavIcon,
  },
  "sa-other": {
    name: "sa-other",
    sourceComponent: "SaOtherSideNavIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 20 20",
    category: "navigation",
    labelZh: "侧导航分析 / 其他",
    figmaName: "sa-other",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 分析专属虚拟二级 / 其他", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SaOtherSideNavIcon,
  },
  "sbp-setting": {
    name: "sbp-setting",
    sourceComponent: "SbpSettingSideNavIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 20 20",
    category: "navigation",
    labelZh: "侧导航基本设置",
    figmaName: "sbp-setting",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 单层带图标 / 基本设置", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SbpSettingSideNavIcon,
  },
  "sbp-member": {
    name: "sbp-member",
    sourceComponent: "SbpMemberSideNavIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 20 20",
    category: "navigation",
    labelZh: "侧导航成员管理",
    figmaName: "sbp-member",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 单层带图标 / 成员管理", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SbpMemberSideNavIcon,
  },
  "sbp-role": {
    name: "sbp-role",
    sourceComponent: "SbpRoleSideNavIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 20 20",
    category: "navigation",
    labelZh: "侧导航角色管理",
    figmaName: "sbp-role",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 单层带图标 / 角色管理", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SbpRoleSideNavIcon,
  },
  "default-2": {
    name: "default-2",
    sourceComponent: "Default2SideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航默认图标 2",
    figmaName: "default-2",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 默认兜底 / 默认图标 2", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: Default2SideNavIcon,
  },
  "default-3": {
    name: "default-3",
    sourceComponent: "Default3SideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航默认图标 3",
    figmaName: "default-3",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 默认兜底 / 默认图标 3", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: Default3SideNavIcon,
  },
  "default": {
    name: "default",
    sourceComponent: "DefaultSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航默认图标",
    figmaName: "default",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 默认兜底 / 默认图标", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: DefaultSideNavIcon,
  },
  "sa-dashboard": {
    name: "sa-dashboard",
    sourceComponent: "SaDashboardSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航概览",
    figmaName: "sa-dashboard",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 分析专属 / 概览", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SaDashboardSideNavIcon,
  },
  "sa-dataset": {
    name: "sa-dataset",
    sourceComponent: "SaDatasetSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航业务集市",
    figmaName: "sa-dataset",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 分析专属 / 业务集市", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SaDatasetSideNavIcon,
  },
  "sa-debugging-equipment": {
    name: "sa-debugging-equipment",
    sourceComponent: "SaDebuggingEquipmentSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航调试设备管理",
    figmaName: "sa-debugging-equipment",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 分析专属 / 调试设备管理", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SaDebuggingEquipmentSideNavIcon,
  },
  "sa-management": {
    name: "sa-management",
    sourceComponent: "SaManagementSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航管理中心",
    figmaName: "sa-management",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 分析专属 / 管理中心", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SaManagementSideNavIcon,
  },
  "sa-report": {
    name: "sa-report",
    sourceComponent: "SaReportSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航报表",
    figmaName: "sa-report",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 分析专属 / 报表", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SaReportSideNavIcon,
  },
  "sa-test-ceng": {
    name: "sa-test-ceng",
    sourceComponent: "SaTestCengSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航试验层",
    figmaName: "sa-test-ceng",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 分析专属 / 试验层", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SaTestCengSideNavIcon,
  },
  "sa-test-indicator": {
    name: "sa-test-indicator",
    sourceComponent: "SaTestIndicatorSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航试验指标管理",
    figmaName: "sa-test-indicator",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 分析专属 / 试验指标管理", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SaTestIndicatorSideNavIcon,
  },
  "sa-test-list": {
    name: "sa-test-list",
    sourceComponent: "SaTestListSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航试验列表",
    figmaName: "sa-test-list",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 分析专属 / 试验列表", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SaTestListSideNavIcon,
  },
  "sat-ad-assets": {
    name: "sat-ad-assets",
    sourceComponent: "SatAdAssetsSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航资产",
    figmaName: "sat-ad-assets",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 广告分析 / 资产", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SatAdAssetsSideNavIcon,
  },
  "sat-ad-management-config": {
    name: "sat-ad-management-config",
    sourceComponent: "SatAdManagementConfigSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航管理与配置",
    figmaName: "sat-ad-management-config",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 广告分析 / 管理与配置", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SatAdManagementConfigSideNavIcon,
  },
  "sat-ad-promote": {
    name: "sat-ad-promote",
    sourceComponent: "SatAdPromoteSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航推广",
    figmaName: "sat-ad-promote",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 广告分析 / 推广", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SatAdPromoteSideNavIcon,
  },
  "sat-dashboard": {
    name: "sat-dashboard",
    sourceComponent: "SatDashboardSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航概览",
    figmaName: "sat-dashboard",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 广告分析 / 概览", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SatDashboardSideNavIcon,
  },
  "sat-report": {
    name: "sat-report",
    sourceComponent: "SatReportSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航报表",
    figmaName: "sat-report",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 广告分析 / 报表", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SatReportSideNavIcon,
  },
  "sat-tools": {
    name: "sat-tools",
    sourceComponent: "SatToolsSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航工具",
    figmaName: "sat-tools",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 广告分析 / 工具", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SatToolsSideNavIcon,
  },
  "sbp-approval-data-manage": {
    name: "sbp-approval-data-manage",
    sourceComponent: "SbpApprovalDataManageSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航审批数据管理",
    figmaName: "sbp-approval-data-manage",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 平台 / 审批 / 负载 / 审批数据管理", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SbpApprovalDataManageSideNavIcon,
  },
  "sbp-approval-finish": {
    name: "sbp-approval-finish",
    sourceComponent: "SbpApprovalFinishSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航已办",
    figmaName: "sbp-approval-finish",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 平台 / 审批 / 负载 / 已办", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SbpApprovalFinishSideNavIcon,
  },
  "sbp-approval-initiate": {
    name: "sbp-approval-initiate",
    sourceComponent: "SbpApprovalInitiateSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航已发起",
    figmaName: "sbp-approval-initiate",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 平台 / 审批 / 负载 / 已发起", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SbpApprovalInitiateSideNavIcon,
  },
  "sbp-approval-setting": {
    name: "sbp-approval-setting",
    sourceComponent: "SbpApprovalSettingSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航审批配置",
    figmaName: "sbp-approval-setting",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 平台 / 审批 / 负载 / 审批配置", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SbpApprovalSettingSideNavIcon,
  },
  "sbp-approval-switch": {
    name: "sbp-approval-switch",
    sourceComponent: "SbpApprovalSwitchSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航审批开关",
    figmaName: "sbp-approval-switch",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 平台 / 审批 / 负载 / 审批开关", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SbpApprovalSwitchSideNavIcon,
  },
  "sbp-approval-todo": {
    name: "sbp-approval-todo",
    sourceComponent: "SbpApprovalTodoSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航待办",
    figmaName: "sbp-approval-todo",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 平台 / 审批 / 负载 / 待办", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SbpApprovalTodoSideNavIcon,
  },
  "sbp-email-manage": {
    name: "sbp-email-manage",
    sourceComponent: "SbpEmailManageSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航发件箱管理",
    figmaName: "sbp-email-manage",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 平台 / 审批 / 负载 / 发件箱管理", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SbpEmailManageSideNavIcon,
  },
  "sbp-operation-log": {
    name: "sbp-operation-log",
    sourceComponent: "SbpOperationLogSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航操作日志",
    figmaName: "sbp-operation-log",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 平台 / 审批 / 负载 / 操作日志", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SbpOperationLogSideNavIcon,
  },
  "sbp-overview": {
    name: "sbp-overview",
    sourceComponent: "SbpOverviewSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航全局信息",
    figmaName: "sbp-overview",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 平台 / 审批 / 负载 / 全局信息", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SbpOverviewSideNavIcon,
  },
  "sbp-security-setting": {
    name: "sbp-security-setting",
    sourceComponent: "SbpSecuritySettingSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航平台设置",
    figmaName: "sbp-security-setting",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 平台 / 审批 / 负载 / 平台设置", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SbpSecuritySettingSideNavIcon,
  },
  "sbp-workload-biz-assets": {
    name: "sbp-workload-biz-assets",
    sourceComponent: "SbpWorkloadBizAssetsSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航业务资源",
    figmaName: "sbp-workload-biz-assets",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 平台 / 审批 / 负载 / 业务资源", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SbpWorkloadBizAssetsSideNavIcon,
  },
  "sbp-workload-query-task": {
    name: "sbp-workload-query-task",
    sourceComponent: "SbpWorkloadQueryTaskSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航查询任务",
    figmaName: "sbp-workload-query-task",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 平台 / 审批 / 负载 / 查询任务", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SbpWorkloadQueryTaskSideNavIcon,
  },
  "scms-center": {
    name: "scms-center",
    sourceComponent: "ScmsCenterSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航内容中心",
    figmaName: "scms-center",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 内容中台 / 内容中心", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: ScmsCenterSideNavIcon,
  },
  "scms-setting": {
    name: "scms-setting",
    sourceComponent: "ScmsSettingSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航内容配置",
    figmaName: "scms-setting",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 内容中台 / 内容配置", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: ScmsSettingSideNavIcon,
  },
  "scrm-community-operation": {
    name: "scrm-community-operation",
    sourceComponent: "ScrmCommunityOperationSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航社群运营",
    figmaName: "scrm-community-operation",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation SCRM / 社群运营", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: ScrmCommunityOperationSideNavIcon,
  },
  "scrm-customer-management": {
    name: "scrm-customer-management",
    sourceComponent: "ScrmCustomerManagementSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航客户管理",
    figmaName: "scrm-customer-management",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation SCRM / 客户管理", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: ScrmCustomerManagementSideNavIcon,
  },
  "scrm-marketing-customer": {
    name: "scrm-marketing-customer",
    sourceComponent: "ScrmMarketingCustomerSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航营销获客",
    figmaName: "scrm-marketing-customer",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation SCRM / 营销获客", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: ScrmMarketingCustomerSideNavIcon,
  },
  "scrm-marketing-tasks": {
    name: "scrm-marketing-tasks",
    sourceComponent: "ScrmMarketingTasksSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航营销任务",
    figmaName: "scrm-marketing-tasks",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation SCRM / 营销任务", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: ScrmMarketingTasksSideNavIcon,
  },
  "scrm-material-management": {
    name: "scrm-material-management",
    sourceComponent: "ScrmMaterialManagementSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航素材管理",
    figmaName: "scrm-material-management",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation SCRM / 素材管理", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: ScrmMaterialManagementSideNavIcon,
  },
  "scrm-work-notify": {
    name: "scrm-work-notify",
    sourceComponent: "ScrmWorkNotifySideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航工作提醒",
    figmaName: "scrm-work-notify",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation SCRM / 工作提醒", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: ScrmWorkNotifySideNavIcon,
  },
  "sdg-warehousing": {
    name: "sdg-warehousing",
    sourceComponent: "SdgWarehousingSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航数据接入",
    figmaName: "sdg-warehousing",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 数据接入 / 模型 / 数据接入", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SdgWarehousingSideNavIcon,
  },
  "sdh-data-model-table-manage": {
    name: "sdh-data-model-table-manage",
    sourceComponent: "SdhDataModelTableManageSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航数据表",
    figmaName: "sdh-data-model-table-manage",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 数据接入 / 模型 / 数据表", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SdhDataModelTableManageSideNavIcon,
  },
  "sf-active-marketing": {
    name: "sf-active-marketing",
    sourceComponent: "SfActiveMarketingSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航营销策略",
    figmaName: "sf-active-marketing",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 智能运营二级分组 / 营销策略", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SfActiveMarketingSideNavIcon,
  },
  "sf-scene": {
    name: "sf-scene",
    sourceComponent: "SfSceneSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航场景赋能",
    figmaName: "sf-scene",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 智能运营二级分组 / 场景赋能", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SfSceneSideNavIcon,
  },
  "sf-section": {
    name: "sf-section",
    sourceComponent: "SfSectionSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航资源位运营",
    figmaName: "sf-section",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 智能运营二级分组 / 资源位运营", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SfSectionSideNavIcon,
  },
  "sf-wechat": {
    name: "sf-wechat",
    sourceComponent: "SfWechatSideNavIcon",
    sourceFile: "src/ui/SideNavProductIcons.tsx",
    viewBox: "0 0 60 60",
    category: "navigation",
    labelZh: "侧导航微信互动配置",
    figmaName: "sf-wechat",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [{ scene: "Product Shell Side Navigation 智能运营二级分组 / 微信互动配置", typicalSizes: [20], typicalColorRoles: ["inherit"], reusableAtOtherSizes: false }],
    Component: SfWechatSideNavIcon,
  },
  reload: {
    name: "reload",
    sourceComponent: "ReloadIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "operational",
    labelZh: "刷新 / 重新加载",
    currentColor: true,
    dualTone: false,
    temporary: false,
    usageScenes: [
      {
        scene: "Table 信息区、Select 空态、工具栏刷新入口",
        typicalSizes: [16],
        typicalColorRoles: ["inherit", "subtle"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: ReloadIcon,
  },
  setting: {
    name: "setting",
    sourceComponent: "SettingIcon",
    sourceFile: "src/ui/FieldIcons.tsx",
    viewBox: "0 0 16 16",
    category: "operational",
    labelZh: "设置",
    currentColor: true,
    dualTone: true,
    temporary: false,
    usageScenes: [
      {
        scene: "Table 信息区列设置入口、工具栏设置入口",
        typicalSizes: [16],
        typicalColorRoles: ["inherit", "subtle"],
        reusableAtOtherSizes: true,
      },
    ],
    Component: SettingIcon,
  },
};

/** Figma 线性图标优先覆盖同名历史手写资产；未迁移的历史 Sens 图标继续保留。 */
export const ICON_REGISTRY: Record<IconName, IconRegistryEntry> = {
  ...LEGACY_ICON_REGISTRY,
  ...FIGMA_ICON_REGISTRY,
} as Record<IconName, IconRegistryEntry>;

export const ICON_NAMES = Object.keys(ICON_REGISTRY) as IconName[];
export const FILLED_ICON_REGISTRY: Record<FilledIconName, IconRegistryEntry> = FIGMA_FILLED_ICON_REGISTRY;
export { FILLED_ICON_NAMES } from "./filled-icon-names";
export { COLORFUL_ICON_NAMES } from "./colorful-icon-names";
export { COLORFUL_ICON_REGISTRY };

export function getIconRegistryEntry(name: IconName, variant: IconVariant = "linear"): IconRegistryEntry {
  if (variant === "filled") {
    return FILLED_ICON_REGISTRY[name as FilledIconName];
  }
  if (variant === "colorful") {
    return COLORFUL_ICON_REGISTRY[name as ColorfulIconName];
  }
  return ICON_REGISTRY[name];
}

export function isIconName(value: string): value is IconName {
  return value in ICON_REGISTRY || value in FILLED_ICON_REGISTRY || value in COLORFUL_ICON_REGISTRY;
}
